window.CIVPEDIA_MEDIA = {
  LEADER_HIMIKO: {
    portrait: "images/leaders/icons/himiko_queen_of_wa.png",
    thumbnail: "images/leaders/icons/himiko_queen_of_wa.png",
    portraitAlt: "Himiko, Queen of Wa portrait",
    gallery: [
      {
        src: "images/leaders/icons/himiko_queen_of_wa.png",
        label: "Himiko, Queen of Wa"
      },
      {
        src: "images/leaders/icons/himiko_high_shaman.png",
        label: "Himiko, High Shaman"
      }
    ],
    sources: [
      "https://civilization.fandom.com/wiki/Himiko_%28Civ7%29",
      "https://www.pcgamesn.com/civilization-7/leaders",
      "https://www.method.gg/civ-7/civilization-7-leader-tier-list-find-the-best-civ-to-dominate-the-world"
    ]
  }
};

window.CIVPEDIA_ICON_META = {
  YIELD_SCIENCE: { label: "Science", page: "Science", kind: "science", symbol: "S" },
  YIELD_CULTURE: { label: "Culture", page: "Culture", kind: "culture", symbol: "C" },
  YIELD_DIPLOMACY: { label: "Influence", page: "Influence", kind: "influence", symbol: "I" },
  YIELD_GOLD: { label: "Gold", page: "Gold", kind: "gold", symbol: "G" },
  YIELD_FOOD: { label: "Food", page: "Food", kind: "food", symbol: "F" },
  YIELD_PRODUCTION: { label: "Production", page: "Production", kind: "production", symbol: "P" },
  YIELD_HAPPINESS: { label: "Happiness", page: "Happiness", kind: "happiness", symbol: "H" },
  SPECIALIST: { label: "Specialist", page: "Specialist", kind: "specialist", symbol: "SP" },
  NOTIFICATION_SELECT_CAPITAL: { label: "Capital", page: "Capital", kind: "capital", symbol: "CA" },
  TERRAIN_COAST: { label: "Coastal", page: "Coast", kind: "terrain", symbol: "CO" },
  TERRAIN_DESERT: { label: "Desert", page: "Desert", kind: "terrain", symbol: "DE" },
  TERRAIN_GRASS: { label: "Grassland", page: "Grassland", kind: "terrain", symbol: "GR" },
  TERRAIN_PLAINS: { label: "Plains", page: "Plains", kind: "terrain", symbol: "PL" },
  TERRAIN_TUNDRA: { label: "Tundra", page: "Tundra", kind: "terrain", symbol: "TU" },
  TERRAIN_TROPICAL: { label: "Tropical", page: "Tropical", kind: "terrain", symbol: "TR" },
  TERRAIN_VEGETATED: { label: "Vegetated", page: "Vegetated", kind: "terrain", symbol: "VE" },
  ATTRIBUTE_CULTURAL: { label: "Cultural", page: "Attribute", kind: "culture", symbol: "C" },
  ATTRIBUTE_DIPLOMATIC: { label: "Diplomatic", page: "Attribute", kind: "influence", symbol: "D" },
  ATTRIBUTE_ECONOMIC: { label: "Economic", page: "Attribute", kind: "gold", symbol: "E" },
  ATTRIBUTE_EXPANSIONIST: { label: "Expansionist", page: "Attribute", kind: "terrain", symbol: "X" },
  ATTRIBUTE_MILITARISTIC: { label: "Militaristic", page: "Attribute", kind: "military", symbol: "M" },
  ATTRIBUTE_SCIENTIFIC: { label: "Scientific", page: "Attribute", kind: "science", symbol: "S" },
  ATTRIBUTE_WILDCARD: { label: "Wildcard", page: "Attribute", kind: "wildcard", symbol: "W" },

  // Concept / gameplay tokens referenced by leader ability & agenda text.
  // `img` (optional) overrides the default file name images/icons/<token lowercased>.png.
  YIELD_CITIES: { label: "Cities", page: "City", kind: "capital", symbol: "CT" },
  YIELD_TOWNS: { label: "Towns", page: "Town", kind: "capital", symbol: "TW" },
  YIELD_POPULATION: { label: "Population", page: "Population", kind: "food", symbol: "PO" },
  RADIAL_RESOURCES: { label: "Resources", page: "Resource", kind: "gold", symbol: "R" },
  RADIAL_TECH: { label: "Technology", page: "Technologies", kind: "science", symbol: "T" },
  NAR_REW_COMBAT: { label: "Combat Strength", page: "Combat", kind: "military", symbol: "CS" },
  NAR_REW_GREATWORK: { label: "Great Work", page: "Great Work", kind: "culture", symbol: "GW" },
  NAR_REW_RELIGION: { label: "Religion", page: "Religion", kind: "influence", symbol: "RE" },
  NAR_REW_PROMOTION: { label: "Promotion", page: "Promotions", kind: "military", symbol: "PR" },
  WONDER: { label: "Wonder", page: "Wonders", kind: "wildcard", symbol: "WO" },
  CELEBRATION: { label: "Celebration", page: "Celebration", kind: "happiness", symbol: "CE" },
  TRADE_ROUTE: { label: "Trade Route", page: "Trade Route", kind: "gold", symbol: "TR" },
  GOVERNMENT: { label: "Government", page: "Government", kind: "influence", symbol: "GV" },
  CIVICS: { label: "Civics", page: "Civics", kind: "culture", symbol: "CV" },
  SOCIAL_POLICY: { label: "Social Policy", page: "Social Policies", kind: "culture", symbol: "SP" },
  TRADITION: { label: "Tradition", page: "Traditions", kind: "culture", symbol: "TD" },
  CITY_UNIQUE_QUARTER: { label: "Unique Quarter", page: "Quarters", kind: "production", symbol: "UQ" },
  CITY_URBAN: { label: "Urban District", page: "Quarters", kind: "production", symbol: "UR" },
  CITY_RURAL: { label: "Rural District", page: "Improvements", kind: "food", symbol: "RU" },
  CITY_BUILDING_LIST: { label: "Buildings", page: "Buildings", kind: "production", symbol: "BL" },
  CITY_FORTIFIED: { label: "Fortification", page: "Fortification", kind: "military", symbol: "FT" },
  UNIT_SETTLER: { label: "Settler", page: "Settlement", kind: "terrain", symbol: "SE" },
  UNIT_ARMY_COMMANDER: { label: "Army Commander", page: "Commander", kind: "military", symbol: "AC" },
  UNIT_MERCHANT: { label: "Merchant", page: "Merchant", kind: "gold", symbol: "ME" },
  UNIT_MISSIONARY: { label: "Missionary", page: "Missionary", kind: "influence", symbol: "MI" },
  GROWTH_RATE: { label: "Growth", page: "Growth", kind: "food", symbol: "GR" },
  ECONOMIC_VP: { label: "Economic Victory", page: "Victory", kind: "gold", symbol: "EV" },
  CULTURE_VP: { label: "Cultural Victory", page: "Victory", kind: "culture", symbol: "CV" },
  ACTION_MOVE: { label: "Movement", page: "Movement", kind: "generic", symbol: "MV" },
  ACTION_HEAL: { label: "Heal", page: "Healing", kind: "generic", symbol: "HL" },
  ACTION_RANGED: { label: "Ranged Attack", page: "Combat", kind: "military", symbol: "RG" },
  ACTION_PILLAGE: { label: "Pillage", page: "Pillage", kind: "military", symbol: "PL" },
  TERRAIN_MOUNTAIN: { label: "Mountain", page: "Mountain", kind: "terrain", symbol: "MT" },
  TERRAIN_NAVIGABLE_RIVER: { label: "Navigable River", page: "Navigable River", kind: "terrain", symbol: "NR" },
  TERRAIN_RIVER: { label: "River", page: "River", kind: "terrain", symbol: "RV" },

  ACTION_FORTIFY: { label: "Fortify", page: "Fortification", kind: "military", symbol: "FY" },
  ACTION_SHOWALL: { label: "Sight", page: "Sight", kind: "generic", symbol: "SI" },
  CITY_UNIMPROVED: { label: "Unimproved Tile", page: "Improvements", kind: "food", symbol: "UI" },
  COMMANDER_RADIUS: { label: "Command Radius", page: "Commander", kind: "military", symbol: "CR" },
  MILITARY: { label: "Military", page: "Units", kind: "military", symbol: "ML" },
  DAMAGED: { label: "Damage", page: "Combat", kind: "military", symbol: "DM" },
  DIPLOMATIC_ACTION: { label: "Diplomatic Action", page: "Influence", kind: "influence", symbol: "DA" },
  DEFAULT_PROJECT: { label: "Project", page: "Projects", kind: "production", symbol: "PJ" },
  PROJECT: { label: "Project", page: "Projects", kind: "production", symbol: "PJ" },
  NAR_REW_DEFAULT: { label: "Narrative Event", page: "Narrative Events", kind: "wildcard", symbol: "NE" },
  NAR_REW_TRADITION_SLOT: { label: "Social Policy Slot", page: "Social Policies", kind: "culture", symbol: "PS" },
  NOTIFICATION_DISCOVER_NATURAL_WONDER: { label: "Natural Wonder", page: "Natural Wonder", kind: "terrain", symbol: "NW" },
  NOTIFICATION_IDEOLOGY_CHOSEN: { label: "Ideology", page: "Government", kind: "influence", symbol: "ID" },
  PLOT_BURNING: { label: "Pillage", page: "Pillage", kind: "military", symbol: "PL" },
  UNIT_TREASURE_FLEET: { label: "Treasure Fleet", page: "Treasure Fleet", kind: "gold", symbol: "TF" },
  UNIT_CAUTION: { label: "Caution", page: "Units", kind: "military", symbol: "!" },
  UNIT_HOPLITE: { label: "Hoplite", page: "Hoplite", kind: "military", symbol: "HO" },
  UNIT_GUSA: { label: "Gusa", page: "Gusa", kind: "military", symbol: "GU" },
  UNIT_CHEVALER: { label: "Chevalier", page: "Chevalier", kind: "military", symbol: "CH" },
  UNIT_MIGRANT: { label: "Migrant", page: "Migrant", kind: "food", symbol: "MG" },
  UNIT_FLEET_COMMANDER: { label: "Fleet Commander", page: "Commander", kind: "military", symbol: "FC" },
  ATTRIBUTE_POLITICAL: { label: "Diplomatic", page: "Attribute", kind: "influence", symbol: "D" },
  PLAYER_RELATIONSHIP_ALLIANCE: { label: "Alliance", page: "Diplomacy", kind: "influence", symbol: "AL" },
  PLAYER_RELATIONSHIP_FRIENDLY: { label: "Friendly", page: "Diplomacy", kind: "influence", symbol: "FR" },
  PLAYER_RELATIONSHIP_HELPFUL: { label: "Helpful", page: "Diplomacy", kind: "influence", symbol: "HP" },
  PLAYER_RELATIONSHIP_UNFRIENDLY: { label: "Unfriendly", page: "Diplomacy", kind: "military", symbol: "UF" },
  PLAYER_RELATIONSHIP_HOSTILE: { label: "Hostile", page: "Diplomacy", kind: "military", symbol: "HS" },
  ECONOMIC: { label: "Economic", page: "Attribute", kind: "gold", symbol: "E" },
  CITYSTATE: { label: "City-State", page: "Independent Powers", kind: "influence", symbol: "CS" },
  SCIENCE_VP: { label: "Scientific Victory", page: "Victory", kind: "science", symbol: "SV" },
  WAR: { label: "War", page: "War", kind: "military", symbol: "WR" },
  WAR_SUPPORT: { label: "War Support", page: "War", kind: "military", symbol: "WS" },
  ENDEAVOR: { label: "Endeavor", page: "Endeavors", kind: "influence", symbol: "EN" },
  ESPIONAGE: { label: "Espionage", page: "Espionage", kind: "military", symbol: "ES" },
  SANCTIONS: { label: "Sanctions", page: "Sanctions", kind: "gold", symbol: "SN" },
  RELATIONSHIP: { label: "Relationship", page: "Diplomacy", kind: "influence", symbol: "RL" },
  SETTLEMENT_LIMIT: { label: "Settlement Limit", page: "Settlement", kind: "terrain", symbol: "SL" },
  YIELD_WAREHOUSE: { label: "Warehouse Bonus", page: "Improvements", kind: "production", symbol: "WH" },
  GREATWORK: { label: "Great Work", page: "Great Work", kind: "culture", symbol: "GW" },
  INDEPENDENT_POWER: { label: "Independent Power", page: "Independent Powers", kind: "influence", symbol: "IP" },
  MILITARY_VP: { label: "Dominion", page: "Legacy", kind: "military", symbol: "DO" },
  YIELD_ANGRY: { label: "Unrest", page: "Happiness", kind: "military", symbol: "UN" },
  UNIT_ARMY_COMMANDER: { label: "Army Commander", page: "Commander", kind: "military", symbol: "AC" },
  ACTION_MOVE: { label: "Movement", page: "Movement", kind: "generic", symbol: "MV" },
  RADIAL_CIVICS: { label: "Civic", page: "Civics", kind: "culture", symbol: "CV" },
  CITY_RURAL: { label: "Rural District", page: "Improvements", kind: "food", symbol: "RU" },
  CITY_URBAN: { label: "Urban District", page: "Quarters", kind: "production", symbol: "UR" },
  CITY_FORTIFIED: { label: "Fortification", page: "Fortification", kind: "military", symbol: "FT" },
  CITY_BUILDING_LIST: { label: "Buildings", page: "Buildings", kind: "production", symbol: "BL" },
  GOVERNMENT: { label: "Government", page: "Government", kind: "influence", symbol: "GV" },
  GROWTH_RATE: { label: "Growth", page: "Growth", kind: "food", symbol: "GR" },
  NAR_REW_PROMOTION: { label: "Promotion", page: "Promotions", kind: "military", symbol: "PR" },
  NAR_REW_GREATWORK: { label: "Great Work", page: "Great Work", kind: "culture", symbol: "GW" },
  UNIT: { label: "Unit", page: "Units", kind: "military", symbol: "U" },
  ATTRIBUTE: { label: "Attribute", page: "Attribute", kind: "wildcard", symbol: "AT" },
  HAPPY: { label: "Happy", page: "Happiness", kind: "happiness", symbol: ":)" },
  JOYOUS: { label: "Joyous", page: "Happiness", kind: "happiness", symbol: "JY" },
  ECSTATIC: { label: "Ecstatic", page: "Happiness", kind: "happiness", symbol: "EC" },
  MASTERY: { label: "Mastery", page: "Technologies", kind: "science", symbol: "MA" },
  AGE_ANTIQUITY: { label: "Antiquity Age", page: "Ages", kind: "generic", symbol: "AQ" },
  // Named buildings that appear inline in unit prose -> clickable to their
  // Civilopedia building page.
  HOSPITAL: { label: "Hospital", page: "Hospital", kind: "generic", symbol: "H" },
  TEMPLE: { label: "Temple", page: "Temple", kind: "generic", symbol: "T", img: "building_temple.png" }
};


