// Every Memento as the game's card shows it -- the name, the quotation, the
// functional text, its category, the legend path and level that unlock it.
// Built from the game's mementos.xml, MementoText and legend paths by
// tools/build_mementos.py.
window.CIVPEDIA_MEMENTOS = {
 "Inscribed Sling Bullet": {
  "id": "MEMENTO_FOUNDATION_SLING_BULLET",
  "name": "Inscribed Sling Bullet",
  "text": "[B]+1 [icon:ATTRIBUTE_MILITARISTIC][/B] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Militaristic Attribute[/TIP] Point.",
  "quote": "It reads, \"Catch!\"",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "Foundation",
  "unlock": "Unlock at level 2"
 },
 "Complaint to Ea-nāsir": {
  "id": "MEMENTO_FOUNDATION_EA_NASIR",
  "name": "Complaint to Ea-nāsir",
  "text": "[B]+1 [icon:ATTRIBUTE_ECONOMIC][/B] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Economic Attribute[/TIP] Point.",
  "quote": "Sub-standard copper is unacceptable.",
  "tag": "Economic",
  "tier": "1",
  "level": 2,
  "path": "Foundation",
  "unlock": "Unlock at level 2"
 },
 "Treaty of Kadesh": {
  "id": "MEMENTO_FOUNDATION_TREATY_OF_KADESH",
  "name": "Treaty of Kadesh",
  "text": "[B]+1 [icon:ATTRIBUTE_POLITICAL][/B] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Diplomatic Attribute[/TIP] Point.",
  "quote": "Peace pieces.",
  "tag": "Diplomatic",
  "tier": "1",
  "level": 3,
  "path": "Foundation",
  "unlock": "Unlock at level 3"
 },
 "Groma": {
  "id": "MEMENTO_FOUNDATION_GROMA",
  "name": "Groma",
  "text": "[B]+1 [icon:ATTRIBUTE_EXPANSIONIST][/B] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Expansionist Attribute[/TIP] Point.",
  "quote": "Surveying for centuriation.",
  "tag": "Expansionist",
  "tier": "1",
  "level": 3,
  "path": "Foundation",
  "unlock": "Unlock at level 4"
 },
 "Shakōkidogū": {
  "id": "MEMENTO_FOUNDATION_SHAKOKIDOGU",
  "name": "Shakōkidogū",
  "text": "[B]+1 [icon:ATTRIBUTE_CULTURAL][/B] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Cultural Attribute[/TIP] Point.",
  "quote": "Earthen effigy.",
  "tag": "Cultural",
  "tier": "1",
  "level": 4,
  "path": "Foundation",
  "unlock": "Unlock at level 5"
 },
 "Antikythera Mechanism": {
  "id": "MEMENTO_FOUNDATION_ANTIKYTHERA_MECHANISM",
  "name": "Antikythera Mechanism",
  "text": "[B]+1 [icon:ATTRIBUTE_SCIENTIFIC][/B] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Scientific Attribute[/TIP] Point.",
  "quote": "Its calculations are astronomical.",
  "tag": "Scientific",
  "tier": "1",
  "level": 4,
  "path": "Foundation",
  "unlock": "Unlock at level 6"
 },
 "Sword of Brennus": {
  "id": "MEMENTO_FOUNDATION_SWORD_BRENNUS",
  "name": "Sword of Brennus",
  "text": "[B]+400 [icon:YIELD_GOLD][/B] for every [TIP:LOC_PEDIA_CONCEPTS_SETTLEMENT_TOOLTIP]Settlement[/TIP] returned in a Peace Deal.",
  "quote": "Vae victis!",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "Foundation",
  "unlock": "Unlock at level 7"
 },
 "Lydian Lion": {
  "id": "MEMENTO_FOUNDATION_LYDIAN_LION",
  "name": "Lydian Lion",
  "text": "[B]+200 [icon:YIELD_GOLD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] at the start of an Age.",
  "quote": "Electrum coinage.",
  "tag": "Economic",
  "tier": "1",
  "level": 6,
  "path": "Foundation",
  "unlock": "Unlock at level 8"
 },
 "Imago Mundi": {
  "id": "MEMENTO_FOUNDATION_IMAGO_MUNDI",
  "name": "Imago Mundi",
  "text": "[B]+2 [icon:Action_Showall][/B] [TIP:LOC_PEDIA_CONCEPTS_SIGHT_TOOLTIP]Sight[/TIP] instead of +1 for Scout's Search & Lookout abilities.",
  "quote": "Image of the known world.",
  "tag": "Military",
  "tier": "1",
  "level": 7,
  "path": "Foundation",
  "unlock": "Unlock at level 9"
 },
 "Corpus Juris Civilis": {
  "id": "MEMENTO_FOUNDATION_CORPUS_JURIS_CIVILIS",
  "name": "Corpus Juris Civilis",
  "text": "Start with one extra [icon:NAR_REW_TRADITION_SLOT] Social Policy Slot.",
  "quote": "Prudent legal code.",
  "tag": "Diplomatic",
  "tier": "1",
  "level": 8,
  "path": "Foundation",
  "unlock": "Unlock at level 10"
 },
 "The Travels of Marco Polo": {
  "id": "MEMENTO_FOUNDATION_TRAVELS_MARCO_POLO",
  "name": "The Travels of Marco Polo",
  "text": "[B]+50 [icon:YIELD_GOLD][/B] for every 100 tiles explored by your Units.",
  "quote": "Only half of what was seen.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "Foundation",
  "unlock": "Unlock at level 11"
 },
 "Equestrian Figure": {
  "id": "MEMENTO_FOUNDATION_EQUESTRIAN_FIGURE",
  "name": "Equestrian Figure",
  "text": "+50% Reduction in [icon:UNIT_ARMY_COMMANDER] [TIP:LOC_PEDIA_CONCEPTS_COMMANDER_TOOLTIP]Commander[/TIP] Recovery Time.",
  "quote": "Transportable military.",
  "tag": "Military",
  "tier": "1",
  "level": 14,
  "path": "Foundation",
  "unlock": "Unlock at level 12"
 },
 "Pochteca Backpack": {
  "id": "MEMENTO_FOUNDATION_POCHTECA_BACKPACK",
  "name": "Pochteca Backpack",
  "text": "+5 range for all [icon:TRADE_ROUTE] [TIP:LOC_PEDIA_CONCEPTS_TRADE_ROUTE_TOOLTIP]Trade Routes[/TIP].",
  "quote": "Warrior-merchant chic.",
  "tag": "Economic",
  "tier": "1",
  "level": 19,
  "path": "Foundation",
  "unlock": "Unlock at level 13"
 },
 "Colada & Tizona": {
  "id": "MEMENTO_FOUNDATION_COLADA_TIZONA",
  "name": "Colada & Tizona",
  "text": "[B]+2 [icon:NAR_REW_COMBAT][/B] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] for Units adjacent to 2 or more enemy Units.",
  "quote": "Swords of El Cid.",
  "tag": "Military",
  "tier": "1",
  "level": 24,
  "path": "Foundation",
  "unlock": "Unlock at level 14"
 },
 "Shisa Necklace": {
  "id": "MEMENTO_FOUNDATION_SHISA_NECKLACE",
  "name": "Shisa Necklace",
  "text": "Gain [B]50 [icon:YIELD_DIPLOMACY][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] when you become [TIP:LOC_PEDIA_CONCEPTS_SUZERAIN_TOOLTIP]Suzerain[/TIP] of a [icon:CITYSTATE] [TIP:LOC_PEDIA_CONCEPTS_CITY_STATE_TOOLTIP]City-State[/TIP].",
  "quote": "Guardian lion.",
  "tag": "Military",
  "tier": "1",
  "level": 29,
  "path": "Foundation",
  "unlock": "Unlock at level 15"
 },
 "Agincourt Arrowhead": {
  "id": "MEMENTO_FOUNDATION_AGINCOURT_ARROWHEAD",
  "name": "Agincourt Arrowhead",
  "text": "[B]+1 [icon:Action_Move] Movement[/B] for [TIP:LOC_PEDIA_CONCEPTS_RANGED_UNITS_TOOLTIP]Ranged Units[/TIP].",
  "quote": "Airborne exsanguinator.",
  "tag": "Military",
  "tier": "1",
  "level": 34,
  "path": "Foundation",
  "unlock": "Unlock at level 16"
 },
 "Garuda Statue": {
  "id": "MEMENTO_FOUNDATION_GARUDA_STATUE",
  "name": "Garuda Statue",
  "text": "[B]+1 [icon:YIELD_POPULATION][/B] [TIP:LOC_PEDIA_CONCEPTS_POPULATION_TOOLTIP]Population[/TIP] to your smallest [TIP:LOC_PEDIA_CONCEPTS_SETTLEMENT_TOOLTIP]Settlement[/TIP] every time you start a [icon:CELEBRATION] [TIP:LOC_PEDIA_CONCEPTS_CELEBRATIONS_TOOLTIP]Celebration[/TIP].",
  "quote": "Soaring high.",
  "tag": "Military",
  "tier": "1",
  "level": 39,
  "path": "Foundation",
  "unlock": "Unlock at level 17"
 },
 "The Art of War": {
  "id": "MEMENTO_FOUNDATION_ART_OF_WAR",
  "name": "The Art of War",
  "text": "[B]+10%[/B][TIP:LOC_PEDIA_CONCEPTS_COMMANDER_EXPERIENCE_TOOLTIP]Commander Experience[/TIP]. +50% when within the [TIP:LOC_PEDIA_CONCEPTS_COMMAND_RADIUS_TOOLTIP]Command Radius[/TIP] of a higher level [icon:UNIT_ARMY_COMMANDER] [TIP:LOC_PEDIA_CONCEPTS_COMMANDER_TOOLTIP]Commander[/TIP].",
  "quote": "Of vital importance.",
  "tag": "Military",
  "tier": "1",
  "level": 44,
  "path": "Foundation",
  "unlock": "Unlock at level 18"
 },
 "Royal Game of Ur": {
  "id": "MEMENTO_FOUNDATION_GAME_OF_UR",
  "name": "Royal Game of Ur",
  "text": "[B]+10% [icon:YIELD_SCIENCE][/B] when outpaced in [icon:TECHS] [TIP:LOC_PEDIA_CONCEPTS_TECH_TOOLTIP]Tech[/TIP] by half of Civs. [B]+10% [icon:YIELD_CULTURE][/B] when outpaced in [icon:CIVICS] [TIP:LOC_PEDIA_CONCEPTS_CIVIC_TOOLTIP]Civics[/TIP] by half of Civs.",
  "quote": "Strategic play.",
  "tag": "Military",
  "tier": "1",
  "level": 49,
  "path": "Foundation",
  "unlock": "Unlock at level 19"
 },
 "Takoba": {
  "id": "MEMENTO_AMINA_TAKOBA",
  "name": "Takoba",
  "text": "[B]+1 [icon:NAR_REW_COMBAT][/B] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] for all Units in Plains and Desert.",
  "quote": "A traditional Hausa blade.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "AMINA",
  "unlock": "Unlock at Amina level 2"
 },
 "Kwalkwali": {
  "id": "MEMENTO_AMINA_KWALKWALI",
  "name": "Kwalkwali",
  "text": "[B]+1 [icon:YIELD_GOLD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for each [icon:RADIAL_RESOURCES] [TIP:LOC_PEDIA_CONCEPTS_RESOURCES_TOOLTIP]Resource[/TIP] assigned to [icon:YIELD_CITIES] [TIP:LOC_PEDIA_CONCEPTS_CITIES_TOOLTIP]Cities[/TIP].",
  "quote": "Regal horse headdress.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "AMINA",
  "unlock": "Unlock at Amina level 5"
 },
 "Rawani": {
  "id": "MEMENTO_AMINA_RAWANI",
  "name": "Rawani",
  "text": "[B]+3 [icon:NAR_REW_COMBAT][/B] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] to a Unit's next attack after they defeat an enemy Unit.",
  "quote": "Royal turban.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "AMINA",
  "unlock": "Unlock at Amina level 9"
 },
 "Chakra": {
  "id": "MEMENTO_ASHOKA_RENOUNCER_CHAKRA",
  "name": "Chakra",
  "text": "[B]+1 [icon:YIELD_FOOD][/B] in your [icon:NOTIFICATION_SELECT_CAPITAL] [TIP:LOC_PEDIA_CONCEPTS_CAPITAL_TOOLTIP]Capital[/TIP] for every 5 excess [icon:YIELD_HAPPINESS].",
  "quote": "Turning the wheel.",
  "tag": "Expansionist",
  "tier": "1",
  "level": 2,
  "path": "ASHOKA",
  "unlock": "Unlock at Ashoka, World Renouncer level 2"
 },
 "Gold & Sapphire Flowers": {
  "id": "MEMENTO_ASHOKA_RENOUNCER_GOLD_SAPPHIRE_FLOWERS",
  "name": "Gold & Sapphire Flowers",
  "text": "Gain [B]100 [icon:YIELD_FOOD][/B] in [icon:NOTIFICATION_SELECT_CAPITAL] [TIP:LOC_PEDIA_CONCEPTS_CAPITAL_TOOLTIP]Capital[/TIP] when you spend an [icon:ATTRIBUTE] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Attribute[/TIP] Point on the [icon:ATTRIBUTE_EXPANSIONIST] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Expansionist Attribute[/TIP] Tree. (Scales by Game Speed)",
  "quote": "Blossoms beneath the throne.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "ASHOKA",
  "unlock": "Unlock at Ashoka, World Renouncer level 5"
 },
 "Diamond Throne": {
  "id": "MEMENTO_ASHOKA_RENOUNCER_DIAMOND_THRONE",
  "name": "Diamond Throne",
  "text": "[B]+1 [icon:YIELD_HAPPINESS][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [icon:CITY_UNIQUE_QUARTER] [TIP:LOC_PEDIA_CONCEPTS_UNIQUE_QUARTER_TOOLTIP]Quarters[/TIP] during a [icon:CELEBRATION] [TIP:LOC_PEDIA_CONCEPTS_CELEBRATIONS_TOOLTIP]Celebration[/TIP].",
  "quote": "Location of enlightenment.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "ASHOKA",
  "unlock": "Unlock at Ashoka, World Renouncer level 9"
 },
 "Corona Civica": {
  "id": "MEMENTO_AUGUSTUS_CORONA_CIVICA",
  "name": "Corona Civica",
  "text": "[B]+1 [icon:SETTLEMENT_LIMIT][/B] [TIP:LOC_PEDIA_CONCEPTS_SETTLEMENT_LIMIT_TOOLTIP]Settlement Limit[/TIP] each [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP], but +50% Convert to [icon:YIELD_CITIES] [TIP:LOC_PEDIA_CONCEPTS_CITIES_TOOLTIP]City[/TIP] cost.",
  "quote": "In honor of lives saved.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "AUGUSTUS",
  "unlock": "Unlock at Augustus level 2"
 },
 "Breastplate": {
  "id": "MEMENTO_AUGUSTUS_BREASTPLATE",
  "name": "Breastplate",
  "text": "[B]+2 [icon:YIELD_FOOD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] in [icon:YIELD_TOWNS] [TIP:LOC_PEDIA_CONCEPTS_TOWN_TOOLTIP]Towns[/TIP].",
  "quote": "Made of shining bronze.",
  "tag": "Expansionist",
  "tier": "1",
  "level": 5,
  "path": "AUGUSTUS",
  "unlock": "Unlock at Augustus level 5"
 },
 "Clipeus Virtutis": {
  "id": "MEMENTO_AUGUSTUS_CLIPEUS_VIRTUTIS",
  "name": "Clipeus Virtutis",
  "text": "[B]+1 [icon:YIELD_PRODUCTION][/B] in the [icon:NOTIFICATION_SELECT_CAPITAL] [TIP:LOC_PEDIA_CONCEPTS_CAPITAL_TOOLTIP]Capital[/TIP] for every [icon:YIELD_TOWNS] [TIP:LOC_PEDIA_CONCEPTS_TOWN_TOOLTIP]Town[/TIP].",
  "quote": "Golden recognition.",
  "tag": "Expansionist",
  "tier": "1",
  "level": 9,
  "path": "AUGUSTUS",
  "unlock": "Unlock at Augustus level 9"
 },
 "Bifocals": {
  "id": "MEMENTO_BENJAMIN_FRANKLIN_BIFOCALS",
  "name": "Bifocals",
  "text": "Gain [B]25 [icon:YIELD_DIPLOMACY][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] after researching a [icon:TECHS] [TIP:LOC_PEDIA_CONCEPTS_TECH_TOOLTIP]Technology[/TIP].",
  "quote": "See distinctly, far or near.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "BENJAMIN_FRANKLIN",
  "unlock": "Unlock at Benjamin Franklin level 2"
 },
 "Kite & Key": {
  "id": "MEMENTO_BENJAMIN_FRANKLIN_KITE",
  "name": "Kite & Key",
  "text": "[B]+10% [icon:YIELD_SCIENCE][/B] towards researching [TIP:LOC_PEDIA_CONCEPTS_MASTERY_TOOLTIP]Tech Masteries[/TIP].",
  "quote": "Unravel lightning's mysteries.",
  "tag": "Scientific",
  "tier": "1",
  "level": 5,
  "path": "BENJAMIN_FRANKLIN",
  "unlock": "Unlock at Benjamin Franklin level 5"
 },
 "Glass Armonica": {
  "id": "MEMENTO_BENJAMIN_FRANKLIN_GLASS_ARMONICA",
  "name": "Glass Armonica",
  "text": "[B]+15 [icon:YIELD_SCIENCE][/B] and [icon:YIELD_HAPPINESS] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] when in an [icon:PLAYER_RELATIONSHIP_ALLIANCE] [TIP:LOC_PEDIA_CONCEPTS_ALLIANCE_TOOLTIP]Alliance[/TIP] for you and your [icon:PLAYER_RELATIONSHIP_ALLIANCE] Ally.",
  "quote": "Tones by touch.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "BENJAMIN_FRANKLIN",
  "unlock": "Unlock at Benjamin Franklin level 9"
 },
 "Great Imperial Crown": {
  "id": "MEMENTO_CATHERINE_GREAT_IMPERIAL_CROWN",
  "name": "Great Imperial Crown",
  "text": "[B]+2 [icon:YIELD_SCIENCE][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] in [icon:YIELD_TOWNS] [TIP:LOC_PEDIA_CONCEPTS_TOWN_TOOLTIP]Towns[/TIP] in Tundra.",
  "quote": "Jewels like stars.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "CATHERINE",
  "unlock": ""
 },
 "Potemkin's Sword-Knot": {
  "id": "MEMENTO_CATHERINE_POTEMKINS_SWORD_KNOT",
  "name": "Potemkin's Sword-Knot",
  "text": "[B]+1 [icon:Action_Move] Movement[/B] for [icon:UNIT_ARMY_COMMANDER] [TIP:LOC_PEDIA_CONCEPTS_COMMANDER_TOOLTIP]Commanders[/TIP].",
  "quote": "Gift from a soulmate.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "CATHERINE",
  "unlock": "Unlock at Catherine level 5"
 },
 "Eagle Banner": {
  "id": "MEMENTO_CATHERINE_EAGLE_BANNER",
  "name": "Eagle Banner",
  "text": "[icon:YIELD_CITIES] [TIP:LOC_PEDIA_CONCEPTS_CITIES_TOOLTIP]Cities[/TIP] gain [B]2% [icon:YIELD_SCIENCE][/B] per [icon:NAR_REW_GREATWORK] [TIP:LOC_PEDIA_CONCEPTS_GREAT_WORKS_TOOLTIP]Great Work[/TIP] on display. (Max 20%)",
  "quote": "Imperial legacy.",
  "tag": "Scientific",
  "tier": "1",
  "level": 2,
  "path": "CATHERINE",
  "unlock": "Unlock at Catherine level 9"
 },
 "Joyeuse": {
  "id": "MEMENTO_CHARLEMAGNE_JOYEUSE",
  "name": "Joyeuse",
  "text": "[B]+1 [icon:YIELD_HAPPINESS][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [TIP:LOC_PEDIA_CONCEPTS_CAVALRY_UNITS_TOOLTIP]Cavalry Units[/TIP] [TIP:LOC_PEDIA_CONCEPTS_STATIONED_TOOLTIP]Stationed[/TIP] on a [TIP:LOC_PEDIA_CONCEPTS_PALACE_TOOLTIP]Palace[/TIP] or [icon:YIELD_CITIES] [TIP:LOC_PEDIA_CONCEPTS_CITIES_TOOLTIP]City[/TIP] Hall.",
  "quote": "Happiness, by the slice.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "CHARLEMAGNE",
  "unlock": "Unlock at Charlemagne level 2"
 },
 "Globus Cruciger": {
  "id": "MEMENTO_CHARLEMAGNE_GLOBUS_CRUCIGER",
  "name": "Globus Cruciger",
  "text": "Gain [B]50 [icon:YIELD_DIPLOMACY][/B] when you spend an [icon:ATTRIBUTE] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Attribute[/TIP] Point on the [icon:ATTRIBUTE_POLITICAL] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Diplomatic Attribute[/TIP] Tree. (Scales by Game Speed)",
  "quote": "The world in your hands.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "CHARLEMAGNE",
  "unlock": "Unlock at Charlemagne level 5"
 },
 "Tencendur": {
  "id": "MEMENTO_CHARLEMAGNE_TENCENDUR",
  "name": "Tencendur",
  "text": "[B]+1 [icon:Action_Move] Movement[/B] for [TIP:LOC_PEDIA_CONCEPTS_CAVALRY_UNITS_TOOLTIP]Cavalry Units[/TIP].",
  "quote": "Strife, saddled.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "CHARLEMAGNE",
  "unlock": "Unlock at Charlemagne level 9"
 },
 "Brush & Scroll": {
  "id": "MEMENTO_CONFUCIUS_BRUSH_SCROLL",
  "name": "Brush & Scroll",
  "text": "[B]+5% [icon:GROWTH_RATE][/B] [TIP:LOC_PEDIA_CONCEPTS_GROWTH_RATE_TOOLTIP]Growth Rate[/TIP] in [icon:YIELD_CITIES] [TIP:LOC_PEDIA_CONCEPTS_CITIES_TOOLTIP]Cities[/TIP] for every [icon:SPECIALIST] [TIP:LOC_PEDIA_CONCEPTS_SPECIALIST_TOOLTIP]Specialist[/TIP] in that [icon:YIELD_CITIES] City (Max 25%).",
  "quote": "Wisdom in words.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "CONFUCIUS",
  "unlock": "Unlock at Confucius level 2"
 },
 "Altar Set": {
  "id": "MEMENTO_CONFUCIUS_ALTAR_SET",
  "name": "Altar Set",
  "text": "[B]+1 [icon:YIELD_CULTURE][/B] from [icon:SPECIALIST] [TIP:LOC_PEDIA_CONCEPTS_SPECIALIST_TOOLTIP]Specialists[/TIP].",
  "quote": "Preserving the rites.",
  "tag": "Cultural",
  "tier": "1",
  "level": 5,
  "path": "CONFUCIUS",
  "unlock": "Unlock at Confucius level 5"
 },
 "The Analects": {
  "id": "MEMENTO_CONFUCIUS_ANALECTS",
  "name": "The Analects",
  "text": "[B]+1 [icon:YIELD_SCIENCE][/B] from [icon:SPECIALIST] [TIP:LOC_PEDIA_CONCEPTS_SPECIALIST_TOOLTIP]Specialists[/TIP].",
  "quote": "Sayings of the sage.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "CONFUCIUS",
  "unlock": "Unlock at Confucius level 9"
 },
 "Walking Stick": {
  "id": "MEMENTO_FRIEDRICH_OBLIQUE_WALKING_STICK",
  "name": "Walking Stick",
  "text": "[B]+1 [icon:YIELD_SCIENCE][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [TIP:LOC_PEDIA_CONCEPTS_BUILDINGS_TOOLTIP]Military Buildings[/TIP].",
  "quote": "Cane-supported cadence.",
  "tag": "Scientific",
  "tier": "1",
  "level": 2,
  "path": "FRIEDRICH",
  "unlock": "Unlock at Friedrich, Oblique level 2"
 },
 "Order of the Black Eagle Badge": {
  "id": "MEMENTO_FRIEDRICH_OBLIQUE_ORDER_BLACK_EAGLE",
  "name": "Order of the Black Eagle Badge",
  "text": "Gain [B]50 [icon:YIELD_PRODUCTION][/B] when you spend an [icon:ATTRIBUTE] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Attribute[/TIP] Point on the [icon:ATTRIBUTE_MILITARISTIC] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Militaristic Attribute[/TIP] Tree. (Scales by Game Speed)",
  "quote": "Highest order of chivalry.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "FRIEDRICH",
  "unlock": "Unlock at Friedrich, Oblique level 5"
 },
 "Krone von Friedrich I": {
  "id": "MEMENTO_FRIEDRICH_OBLIQUE_KRONE_VON_FRIEDRICH",
  "name": "Krone von Friedrich I",
  "text": "[B]+2 [icon:NAR_REW_COMBAT][/B] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] for all Units when using Coordinated Attack or Focus Fire.",
  "quote": "From Soldier King to son.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "FRIEDRICH",
  "unlock": "Unlock at Friedrich, Oblique level 9"
 },
 "Lantern": {
  "id": "MEMENTO_TUBMAN_LANTERN",
  "name": "Lantern",
  "text": "Gain a [icon:UNIT_MIGRANT] Migrant in the [icon:NOTIFICATION_SELECT_CAPITAL] [TIP:LOC_PEDIA_CONCEPTS_CAPITAL_TOOLTIP]Capital[/TIP] when you complete an undetected [icon:ESPIONAGE] [TIP:LOC_PEDIA_CONCEPTS_ESPIONAGE_TOOLTIP]Espionage[/TIP] Action.",
  "quote": "A guiding light.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "HARRIET_TUBMAN",
  "unlock": "Unlock at Harriet Tubman level 2"
 },
 "Satchel": {
  "id": "MEMENTO_TUBMAN_SATCHEL",
  "name": "Satchel",
  "text": "If a [icon:UNIT_SETTLER] Settler is defeated, it respawns in your [icon:NOTIFICATION_SELECT_CAPITAL] [TIP:LOC_PEDIA_CONCEPTS_CAPITAL_TOOLTIP]Capital[/TIP] after 3 turns (on Standard speed).",
  "quote": "Provisions for passengers.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "HARRIET_TUBMAN",
  "unlock": "Unlock at Harriet Tubman level 5"
 },
 "Sidearm": {
  "id": "MEMENTO_TUBMAN_SIDEARM",
  "name": "Sidearm",
  "text": "[B]+3 [icon:NAR_REW_COMBAT][/B] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] to your Units below 50% health.",
  "quote": "Death or liberty.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "HARRIET_TUBMAN",
  "unlock": "Unlock at Harriet Tubman level 9"
 },
 "Royal Mace": {
  "id": "MEMENTO_HATSHEPSUT_ROYAL_MACE",
  "name": "Royal Mace",
  "text": "[B]+1 [icon:YIELD_GOLD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for each imported [icon:RADIAL_RESOURCES] [TIP:LOC_PEDIA_CONCEPTS_RESOURCES_TOOLTIP]Resource[/TIP].",
  "quote": "A symbol of authority.",
  "tag": "Economic",
  "tier": "1",
  "level": 2,
  "path": "HATSHEPSUT",
  "unlock": "Unlock at Hatshepsut level 2"
 },
 "False Beard": {
  "id": "MEMENTO_HATSHEPSUT_FALSE_BEARD",
  "name": "False Beard",
  "text": "[B]+2 [icon:YIELD_CULTURE][/B] on [icon:WONDER] [TIP:LOC_PEDIA_CONCEPTS_WONDERS_TOOLTIP]Wonders[/TIP].",
  "quote": "Horus incarnate.",
  "tag": "Cultural",
  "tier": "1",
  "level": 5,
  "path": "HATSHEPSUT",
  "unlock": "Unlock at Hatshepsut level 5"
 },
 "Uraeus": {
  "id": "MEMENTO_HATSHEPSUT_URAEUS",
  "name": "Uraeus",
  "text": "[B]+10 [icon:YIELD_CULTURE][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] in [icon:YIELD_CITIES] [TIP:LOC_PEDIA_CONCEPTS_CITIES_TOOLTIP]Cities[/TIP] with at least [B]1 [icon:WONDER][/B] [TIP:LOC_PEDIA_CONCEPTS_WONDERS_TOOLTIP]Wonder[/TIP].",
  "quote": "Serpentine symbol of sovereignty.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "HATSHEPSUT",
  "unlock": "Unlock at Hatshepsut level 9"
 },
 "Golden Seal Stone": {
  "id": "MEMENTO_HIMIKO_QUEEN_GOLDEN_SEAL_STONE",
  "name": "Golden Seal Stone",
  "text": "[B]+1 [icon:YIELD_DIPLOMACY][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [TIP:LOC_PEDIA_CONCEPTS_BUILDINGS_TOOLTIP]Science Buildings[/TIP].",
  "quote": "Gift from an emperor.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "HIMIKO",
  "unlock": "Unlock at Himiko, Queen of Wa level 2"
 },
 "Yasakani no Magatama": {
  "id": "MEMENTO_HIMIKO_QUEEN_YASAKANI_NO_MAGATAMA",
  "name": "Yasakani no Magatama",
  "text": "[B]+2 [icon:YIELD_SCIENCE][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for every [TIP:LOC_PEDIA_CONCEPTS_TECH_TOOLTIP]Technology[/TIP] [TIP:LOC_PEDIA_CONCEPTS_MASTERY_TOOLTIP]Mastery[/TIP] completed.",
  "quote": "Represents benevolence.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "HIMIKO",
  "unlock": "Unlock at Himiko, Queen of Wa level 9"
 },
 "Dōtaku": {
  "id": "MEMENTO_HIMIKO_QUEEN_DOTAKU",
  "name": "Dōtaku",
  "text": "Gain [B]50 [icon:YIELD_SCIENCE][/B] when you spend an [icon:ATTRIBUTE] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Attribute[/TIP] Point on the [icon:ATTRIBUTE_SCIENTIFIC] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Scientific Attribute[/TIP] Tree. (Scales by Game Speed)",
  "quote": "Friend of the Harvest.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "HIMIKO",
  "unlock": "Unlock at Himiko, Queen of Wa level 5"
 },
 "Traveller's Sandals": {
  "id": "MEMENTO_BATTUTA_TRAVELLERS_SANDALS",
  "name": "Traveller's Sandals",
  "text": "Gain 25 of the corresponding yield whenever you spend an [icon:ATTRIBUTE] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Attribute[/TIP] Point. (Scales by Game Speed)",
  "quote": "Marked by many miles.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "IBN_BATTUTA",
  "unlock": "Unlock at Ibn Battuta level 2"
 },
 "Merchant's Saddle": {
  "id": "MEMENTO_BATTUTA_MERCHANTS_SADDLE",
  "name": "Merchant's Saddle",
  "text": "[B]+1 [icon:Action_Move] Movement[/B] for Scouts, [icon:UNIT_MERCHANT] Merchants, [icon:UNIT_SETTLER] Settlers, and Explorers.",
  "quote": "Backbone of commerce.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "IBN_BATTUTA",
  "unlock": "Unlock at Ibn Battuta level 5"
 },
 "The Rihla": {
  "id": "MEMENTO_BATTUTA_RIHLA",
  "name": "The Rihla",
  "text": "[B]+1 [icon:YIELD_CULTURE][/B], [icon:YIELD_GOLD], [icon:YIELD_HAPPINESS], and [icon:YIELD_SCIENCE] per turn per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for each [icon:ATTRIBUTE] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Attribute Tree[/TIP] in which you have points.",
  "quote": "The Marvels of Traveling.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "IBN_BATTUTA",
  "unlock": "Unlock at Ibn Battuta level 9"
 },
 "Queen's Jewelry": {
  "id": "MEMENTO_ISABELLA_QUEENS_JEWELRY",
  "name": "Queen's Jewelry",
  "text": "[B]+2 [icon:YIELD_GOLD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [icon:NOTIFICATION_DISCOVER_NATURAL_WONDER] [TIP:LOC_PEDIA_CONCEPTS_NATURAL_WONDER_TOOLTIP]Natural Wonders[/TIP].",
  "quote": "Royal regalia.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "ISABELLA",
  "unlock": "Unlock at Isabella level 2"
 },
 "Ballestilla": {
  "id": "MEMENTO_ISABELLA_BALLESTILLA",
  "name": "Ballestilla",
  "text": "[B]+1 [icon:Action_Showall][/B] [TIP:LOC_PEDIA_CONCEPTS_SIGHT_TOOLTIP]Sight[/TIP] for [TIP:LOC_PEDIA_CONCEPTS_NAVAL_UNITS_TOOLTIP]Naval Units[/TIP].",
  "quote": "Ensures proper latitude.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "ISABELLA",
  "unlock": "Unlock at Isabella level 5"
 },
 "Padrón Real": {
  "id": "MEMENTO_ISABELLA_PADRON_REAL",
  "name": "Padrón Real",
  "text": "[B]+2 [icon:YIELD_HAPPINESS][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [icon:NOTIFICATION_DISCOVER_NATURAL_WONDER] [TIP:LOC_PEDIA_CONCEPTS_NATURAL_WONDER_TOOLTIP]Natural Wonders[/TIP].",
  "quote": "Secrets mapped and royally registered.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "ISABELLA",
  "unlock": "Unlock at Isabella level 9"
 },
 "Forget-me-not": {
  "id": "MEMENTO_RIZAL_FORGET_ME_NOT",
  "name": "Forget-me-not",
  "text": "Gain [B]10 [icon:YIELD_HAPPINESS][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for completing Narrative Events.",
  "quote": "Sown by the traveler.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "JOSE_RIZAL",
  "unlock": "Unlock at José Rizal level 2"
 },
 "Ophthalmoscope": {
  "id": "MEMENTO_RIZAL_OPHTHALMOSCOPE",
  "name": "Ophthalmoscope",
  "text": "[B]+25% [icon:CELEBRATION][/B] [TIP:LOC_PEDIA_CONCEPTS_CELEBRATIONS_TOOLTIP]Celebration[/TIP] Duration.",
  "quote": "Clarity of vision.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "JOSE_RIZAL",
  "unlock": "Unlock at José Rizal level 5"
 },
 "Noli Me Tángere": {
  "id": "MEMENTO_RIZAL_NOLI_ME_TANGERE",
  "name": "Noli Me Tángere",
  "text": "[B]+1 [icon:YIELD_SCIENCE][/B], [icon:YIELD_CULTURE], and [icon:YIELD_GOLD] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for each [TIP:LOC_PEDIA_CONCEPTS_MAJOR_TRIUMPH_TOOLTIP]Major Triumph[/TIP] completed in an Age.",
  "quote": "To my country.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "JOSE_RIZAL",
  "unlock": "Unlock at José Rizal level 9"
 },
 "Letter to Adrienne": {
  "id": "MEMENTO_LAFAYETTE_LETTER_ADRIENNE",
  "name": "Letter to Adrienne",
  "text": "[B]+2 [icon:YIELD_HAPPINESS][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for each [icon:SOCIAL_POLICY] [TIP:LOC_PEDIA_CONCEPTS_SOCIAL_POLICY_TOOLTIP]Social Policy[/TIP] slotted in your [icon:GOVERNMENT] [TIP:LOC_PEDIA_CONCEPTS_GOVERNMENT_TOOLTIP]Government[/TIP].",
  "quote": "The happiness of all mankind.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "LAFAYETTE",
  "unlock": "Unlock at Lafayette level 2"
 },
 "Hermione Model": {
  "id": "MEMENTO_LAFAYETTE_HERMIONE_MODEL",
  "name": "Hermione Model",
  "text": "[B]+1 [icon:Action_Move] Movement[/B] to all [TIP:LOC_PEDIA_CONCEPTS_NAVAL_UNITS_TOOLTIP]Naval Units[/TIP].",
  "quote": "Concorde-class frigate.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "LAFAYETTE",
  "unlock": "Unlock at Lafayette level 5"
 },
 "Tricolor Cockade": {
  "id": "MEMENTO_LAFAYETTE_TRICOLOUR_COCKADE",
  "name": "Tricolor Cockade",
  "text": "[B]+2 [icon:YIELD_CULTURE][/B] and [icon:YIELD_HAPPINESS] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] in the [icon:NOTIFICATION_SELECT_CAPITAL] [TIP:LOC_PEDIA_CONCEPTS_CAPITAL_TOOLTIP]Capital[/TIP] for every [icon:TRADITION] [TIP:LOC_PEDIA_CONCEPTS_TRADITION_TOOLTIP]Tradition[/TIP], but not [icon:SOCIAL_POLICY] [TIP:LOC_PEDIA_CONCEPTS_SOCIAL_POLICY_TOOLTIP]Policy[/TIP], slotted into your [icon:GOVERNMENT] [TIP:LOC_PEDIA_CONCEPTS_GOVERNMENT_TOOLTIP]Government[/TIP].",
  "quote": "Representative ribbon.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "LAFAYETTE",
  "unlock": "Unlock at Lafayette level 9"
 },
 "Discorsi sopra Livio": {
  "id": "MEMENTO_MACHIAVELLI_DISCORSI_SOPRA_LIVIO",
  "name": "Discorsi sopra Livio",
  "text": "Costs opponents 50% more [icon:YIELD_DIPLOMACY] to reject your Diplomatic Actions.",
  "quote": "Longevity requires renewal.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "MACHIAVELLI",
  "unlock": "Unlock at Machiavelli level 2"
 },
 "Dell'Arte della Guerra": {
  "id": "MEMENTO_MACHIAVELLI_DELL_ARTE_DELLA_GUERRA",
  "name": "Dell'Arte della Guerra",
  "text": "[B]+3 [icon:YIELD_GOLD][/B] per [icon:SANCTIONS] [TIP:LOC_PEDIA_CONCEPTS_SANCTION_TOOLTIP]Sanction[/TIP] you have active per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP].",
  "quote": "The only concern to one who commands.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "MACHIAVELLI",
  "unlock": "Unlock at Machiavelli level 5"
 },
 "Il Principe": {
  "id": "MEMENTO_MACHIAVELLI_IL_PRINCIPE",
  "name": "Il Principe",
  "text": "Declaring a [icon:WAR] [TIP:LOC_PEDIA_CONCEPTS_FORMAL_WAR_TOOLTIP]Formal War[/TIP] decreases target's [icon:RELATIONSHIP] [TIP:LOC_PEDIA_CONCEPTS_RELATIONSHIP_TOOLTIP]Relationship[/TIP] with all other Civs by 25.",
  "quote": "Concerning cruelty and clemency.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "MACHIAVELLI",
  "unlock": "Unlock at Machiavelli level 9"
 },
 "Topayauri": {
  "id": "MEMENTO_PACHACUTI_TOPAYAURI",
  "name": "Topayauri",
  "text": "[B]+1 [icon:YIELD_FOOD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [icon:CITY_URBAN] [TIP:LOC_PEDIA_CONCEPTS_DISTRICT_TOOLTIP]Districts[/TIP] adjacent to Mountains.",
  "quote": "Symbol of power and prestige.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "PACHACUTI",
  "unlock": "Unlock at Pachacuti level 2"
 },
 "All-T'oqapu Tunic": {
  "id": "MEMENTO_PACHACUTI_ALL_TOQAPU_TUNIC",
  "name": "All-T'oqapu Tunic",
  "text": "[B]+1 [icon:Action_Showall][/B] [TIP:LOC_PEDIA_CONCEPTS_SIGHT_TOOLTIP]Sight[/TIP] for Scouts adjacent to Mountains.",
  "quote": "Fine cloth, geometric motifs.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "PACHACUTI",
  "unlock": "Unlock at Pachacuti level 5"
 },
 "Mascapaycha": {
  "id": "MEMENTO_PACHACUTI_MASCAPAYCHA",
  "name": "Mascapaycha",
  "text": "[B]+1 [icon:YIELD_GOLD][/B] from [icon:SPECIALIST] [TIP:LOC_PEDIA_CONCEPTS_SPECIALIST_TOOLTIP]Specialists[/TIP]. +1 additional [icon:YIELD_GOLD] from [icon:SPECIALIST] Specialists in tiles adjacent to Mountains.",
  "quote": "Imperial crown of the Tawantinsuyu.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "PACHACUTI",
  "unlock": "Unlock at Pachacuti level 9"
 },
 "Kiem": {
  "id": "MEMENTO_TRUNG_KIEM",
  "name": "Kiem",
  "text": "[B]+2 [icon:YIELD_SCIENCE][/B] for each [icon:UNIT_ARMY_COMMANDER] [TIP:LOC_PEDIA_CONCEPTS_COMMANDER_TOOLTIP]Army Commander[/TIP] [TIP:LOC_PEDIA_CONCEPTS_PROMOTION_TOOLTIP]Promotion[/TIP].",
  "quote": "Rebellious blade.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "TRUNG_TRAC",
  "unlock": ""
 },
 "Ankus": {
  "id": "MEMENTO_TRUNG_ANKUS",
  "name": "Ankus",
  "text": "[B]+1 [icon:WAR_SUPPORT][/B] [TIP:LOC_PEDIA_CONCEPTS_WAR_SUPPORT_TOOLTIP]War Support[/TIP] on all wars.",
  "quote": "Elephantine encouragement.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "TRUNG_TRAC",
  "unlock": "Unlock at Trung Trac level 5"
 },
 "Dong Son Drum": {
  "id": "MEMENTO_TRUNG_DONG_SON_DRUM",
  "name": "Dong Son Drum",
  "text": "Declaring a [icon:WAR] [TIP:LOC_PEDIA_CONCEPTS_FORMAL_WAR_TOOLTIP]Formal War[/TIP] against another Civilization grants a [icon:TECHS] [TIP:LOC_PEDIA_CONCEPTS_TECH_TOOLTIP]Tech[/TIP] Boost.",
  "quote": "Sacred sound.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "TRUNG_TRAC",
  "unlock": "Unlock at Trung Trac level 9"
 },
 "Scythian Battle-Axe": {
  "id": "MEMENTO_XERXES_KING_SCYTHIAN_AXE",
  "name": "Scythian Battle-Axe",
  "text": "[B]+1 [icon:YIELD_GOLD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for every [icon:UNIT_ARMY_COMMANDER] [TIP:LOC_PEDIA_CONCEPTS_COMMANDER_TOOLTIP]Commander[/TIP] [TIP:LOC_PEDIA_CONCEPTS_COMMANDER_EXPERIENCE_TOOLTIP]XP[/TIP] earned.",
  "quote": "To guard the throne.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "XERXES",
  "unlock": "Unlock at Xerxes, King of Kings level 2"
 },
 "Lotus Blossom": {
  "id": "MEMENTO_XERXES_KING_LOTUS_BLOSSOM",
  "name": "Lotus Blossom",
  "text": "Gain [icon:YIELD_SCIENCE] and [icon:YIELD_CULTURE] per turn equal to 4% of your [icon:YIELD_GOLD] income.",
  "quote": "Held in hand.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "XERXES",
  "unlock": "Unlock at Xerxes, King of Kings level 5"
 },
 "Golden Sceptre": {
  "id": "MEMENTO_XERXES_KING_GOLDEN_SCEPTRE",
  "name": "Golden Sceptre",
  "text": "[B]+3 [icon:YIELD_GOLD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for each other Civilization's [TIP:LOC_PEDIA_CONCEPTS_SETTLEMENT_TOOLTIP]Settlement[/TIP] you have conquered.",
  "quote": "Extends favor.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "XERXES",
  "unlock": "Unlock at Xerxes, King of Kings level 9"
 },
 "Punch Cards": {
  "id": "MEMENTO_ADA_LOVELACE_PUNCH_CARDS",
  "name": "Punch Cards",
  "text": "Gain [B]20 [icon:YIELD_SCIENCE][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for every [TIP:LOC_PEDIA_CONCEPTS_BUILDINGS_TOOLTIP]Science Building[/TIP] constructed.",
  "quote": "From loom to computer.",
  "tag": "Scientific",
  "tier": "1",
  "level": 2,
  "path": "ADA_LOVELACE",
  "unlock": "Unlock at Ada Lovelace level 2"
 },
 "Piano": {
  "id": "MEMENTO_ADA_LOVELACE_PIANO",
  "name": "Piano",
  "text": "[B]+10% [icon:YIELD_CULTURE][/B] towards studying [TIP:LOC_PEDIA_CONCEPTS_MASTERY_TOOLTIP]Civic Masteries[/TIP].",
  "quote": "Merging music and math.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "ADA_LOVELACE",
  "unlock": "Unlock at Ada Lovelace level 5"
 },
 "Note G": {
  "id": "MEMENTO_ADA_LOVELACE_NOTE_G",
  "name": "Note G",
  "text": "Every time you research a [TIP:LOC_PEDIA_CONCEPTS_TECH_TOOLTIP]Technology[/TIP] or [TIP:LOC_PEDIA_CONCEPTS_MASTERY_TOOLTIP]Civic Mastery[/TIP], the [icon:NOTIFICATION_SELECT_CAPITAL] [TIP:LOC_PEDIA_CONCEPTS_CAPITAL_TOOLTIP]Capital[/TIP] gains [icon:YIELD_PRODUCTION] equal to 15% of its cost.",
  "quote": "Vision of the future.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "ADA_LOVELACE",
  "unlock": "Unlock at Ada Lovelace level 9"
 },
 "The Iliad": {
  "id": "MEMENTO_ALEXANDER_ILIAD",
  "name": "The Iliad",
  "text": "[B]+1 [icon:YIELD_CULTURE][/B] and [icon:YIELD_PRODUCTION] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [icon:WONDER] [TIP:LOC_PEDIA_CONCEPTS_WONDERS_TOOLTIP]Wonders[/TIP] in [icon:YIELD_CITIES] [TIP:LOC_PEDIA_CONCEPTS_CITIES_TOOLTIP]Cities[/TIP] other than your [icon:NOTIFICATION_SELECT_CAPITAL] [TIP:LOC_PEDIA_CONCEPTS_CAPITAL_TOOLTIP]Capital[/TIP].",
  "quote": "To be a hero.",
  "tag": "Cultural",
  "tier": "1",
  "level": 2,
  "path": "ALEXANDER",
  "unlock": "Unlock at Alexander The Great level 2"
 },
 "Gordian Knot": {
  "id": "MEMENTO_ALEXANDER_DIADEM",
  "name": "Gordian Knot",
  "text": "[B]+1 [icon:SETTLEMENT_LIMIT][/B] [TIP:LOC_PEDIA_CONCEPTS_SETTLEMENT_LIMIT_TOOLTIP]Settlement Limit[/TIP] in each [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP]. [B]+1 [icon:YIELD_GOLD][/B] [TIP:LOC_PEDIA_CONCEPTS_MAINTENANCE_TOOLTIP]Maintenance[/TIP] per Age on all [TIP:LOC_PEDIA_CONCEPTS_LAND_UNITS_TOOLTIP]Land Units[/TIP].",
  "quote": "Destined to rule.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "ALEXANDER",
  "unlock": "Unlock at Alexander The Great level 5"
 },
 "Bridle of Bucephalus": {
  "id": "MEMENTO_ALEXANDER_BRIDLE_OF_BUCEPHALUS",
  "name": "Bridle of Bucephalus",
  "text": "[B]+3 [icon:NAR_REW_COMBAT][/B] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] for [TIP:LOC_PEDIA_CONCEPTS_CAVALRY_UNITS_TOOLTIP]Cavalry Units[/TIP], but [B]+25% [icon:YIELD_PRODUCTION][/B] and Purchase cost for Cavalry Units.",
  "quote": "Turn him toward the sun.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "ALEXANDER",
  "unlock": "Unlock at Alexander The Great level 9"
 },
 "Chanda-mahasena": {
  "id": "MEMENTO_ASHOKA_CONQUEROR_CHANDA_MAHASENA",
  "name": "Chanda-mahasena",
  "text": "[B]+3 [icon:NAR_REW_COMBAT][/B] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] against [icon:CITY_FORTIFIED] [TIP:LOC_PEDIA_CONCEPTS_FORTIFIED_DISTRICTS_TOOLTIP]Fortified Districts[/TIP] for all Units during a [icon:CELEBRATION] [TIP:LOC_PEDIA_CONCEPTS_CELEBRATIONS_TOOLTIP]Celebration[/TIP].",
  "quote": "Vishwakarma's divine creation.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "ASHOKA_ALT",
  "unlock": "Unlock at Ashoka, World Conqueror level 2"
 },
 "Silk Uttariya": {
  "id": "MEMENTO_ASHOKA_CONQUEROR_SILK_UTTARIYA",
  "name": "Silk Uttariya",
  "text": "[B]+2 [icon:YIELD_PRODUCTION][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] in Happy or happier [icon:YIELD_CITIES] [TIP:LOC_PEDIA_CONCEPTS_CITIES_TOOLTIP]Cities[/TIP].",
  "quote": "Faithfully fashioned.",
  "tag": "Expansionist",
  "tier": "1",
  "level": 5,
  "path": "ASHOKA_ALT",
  "unlock": "Unlock at Ashoka, World Conqueror level 5"
 },
 "Lion Capital": {
  "id": "MEMENTO_ASHOKA_CONQUEROR_LION_CAPITAL",
  "name": "Lion Capital",
  "text": "[icon:UNIT_ARMY_COMMANDER] [TIP:LOC_PEDIA_CONCEPTS_COMMANDER_TOOLTIP]Commanders[/TIP] receive [B]+50%[/B][TIP:LOC_PEDIA_CONCEPTS_COMMANDER_EXPERIENCE_TOOLTIP]XP[/TIP] during a [icon:CELEBRATION] [TIP:LOC_PEDIA_CONCEPTS_CELEBRATIONS_TOOLTIP]Celebration[/TIP].",
  "quote": "Roar, and set rolling.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "ASHOKA_ALT",
  "unlock": "Unlock at Ashoka, World Conqueror level 9"
 },
 "Sakaki Branch": {
  "id": "MEMENTO_HIMIKO_SHAMAN_SAKAKI_BRANCH",
  "name": "Sakaki Branch",
  "text": "[B]+25% [icon:YIELD_PRODUCTION][/B] towards constructing [TIP:LOC_PEDIA_CONCEPTS_BUILDINGS_TOOLTIP]Happiness Buildings[/TIP].",
  "quote": "Marks the sacred.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "HIMIKO_ALT",
  "unlock": "Unlock at Himiko, High Shaman level 5"
 },
 "Yata no Kagami": {
  "id": "MEMENTO_HIMIKO_SHAMAN_YATA_NO_KAGAMI",
  "name": "Yata no Kagami",
  "text": "Gain [B]20 [icon:YIELD_CULTURE][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] at the start of every [icon:CELEBRATION] [TIP:LOC_PEDIA_CONCEPTS_CELEBRATIONS_TOOLTIP]Celebration[/TIP].",
  "quote": "Represents wisdom.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "HIMIKO_ALT",
  "unlock": "Unlock at Himiko, High Shaman level 2"
 },
 "Kusanagi no Tsurugi": {
  "id": "MEMENTO_HIMIKO_SHAMAN_KUSANAGI_NO_TSURUGI",
  "name": "Kusanagi no Tsurugi",
  "text": "[B]+3 [icon:YIELD_CULTURE][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [TIP:LOC_PEDIA_CONCEPTS_BUILDINGS_TOOLTIP]Happiness Buildings[/TIP] BUT [B]-1 [icon:YIELD_SCIENCE][/B] per Age on Happiness Buildings.",
  "quote": "Represents valor.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "HIMIKO_ALT",
  "unlock": "Unlock at Himiko, High Shaman level 9"
 },
 "Gold Snuff Box": {
  "id": "MEMENTO_BOLIVAR_GOLD_SNUFF_BOX",
  "name": "Gold Snuff Box",
  "text": "[B]+20 [icon:YIELD_FOOD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] in Cities when in only one [icon:PLAYER_RELATIONSHIP_ALLIANCE] [TIP:LOC_PEDIA_CONCEPTS_ALLIANCE_TOOLTIP]Alliance[/TIP].",
  "quote": "Gift from a royal.",
  "tag": "Expansionist",
  "tier": "1",
  "level": 2,
  "path": "BOLIVAR",
  "unlock": "Unlock at Simón Bolívar level 2"
 },
 "Davalos Medal": {
  "id": "MEMENTO_BOLIVAR_DAVALOS_MEDAL",
  "name": "Davalos Medal",
  "text": "[B]+1 [icon:YIELD_HAPPINESS][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [TIP:LOC_PEDIA_CONCEPTS_BUILDINGS_TOOLTIP]Military Buildings[/TIP].",
  "quote": "Legacy of Ayacucho.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "BOLIVAR",
  "unlock": "Unlock at Simón Bolívar level 5"
 },
 "Letter to Jamaica": {
  "id": "MEMENTO_BOLIVAR_LETTER_TO_JAMAICA",
  "name": "Letter to Jamaica",
  "text": "[B]+50% [icon:YIELD_GOLD][/B] towards purchasing Units during a [icon:CELEBRATION] [TIP:LOC_PEDIA_CONCEPTS_CELEBRATIONS_TOOLTIP]Celebration[/TIP].",
  "quote": "Vision of the future.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "BOLIVAR",
  "unlock": "Unlock at Simón Bolívar level 9"
 },
 "Brace of Pistols": {
  "id": "MEMENTO_EDWARD_TEACH_BRACE_OF_PISTOLS",
  "name": "Brace of Pistols",
  "text": "[B]+2 [icon:NAR_REW_COMBAT][/B] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] for [TIP:LOC_PEDIA_CONCEPTS_NAVAL_UNITS_TOOLTIP]Naval Units[/TIP] while attacking.",
  "quote": "Let the battle commence.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "EDWARD_TEACH",
  "unlock": "Unlock at Edward Teach level 2"
 },
 "Medicine Chest": {
  "id": "MEMENTO_EDWARD_TEACH_MEDICINE_CHEST",
  "name": "Medicine Chest",
  "text": "+5 Healing for [TIP:LOC_PEDIA_CONCEPTS_NAVAL_UNITS_TOOLTIP]Naval Units[/TIP].",
  "quote": "A cure for all ailments.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "EDWARD_TEACH",
  "unlock": "Unlock at Edward Teach level 5"
 },
 "Figurehead of the Queen Anne's Revenge": {
  "id": "MEMENTO_EDWARD_TEACH_FIGUREHEAD_OF_QUEEN_ANNES_REVENGE",
  "name": "Figurehead of the Queen Anne's Revenge",
  "text": "Defeating any Naval Unit grants [icon:YIELD_GOLD] equal to 25% of its [icon:NAR_REW_COMBAT] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP].",
  "quote": "Soaring the seas.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "EDWARD_TEACH",
  "unlock": "Unlock at Edward Teach level 9"
 },
 "Flute": {
  "id": "MEMENTO_FRIEDRICH_BAROQUE_FLUTE",
  "name": "Flute",
  "text": "[B]+1 [icon:YIELD_CULTURE][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [TIP:LOC_PEDIA_CONCEPTS_BUILDINGS_TOOLTIP]Military Buildings[/TIP].",
  "quote": "Carefree melodies.",
  "tag": "Cultural",
  "tier": "1",
  "level": 2,
  "path": "FRIEDRICH_ALT",
  "unlock": "Unlock at Friedrich, Baroque level 2"
 },
 "Voltaire's Edits": {
  "id": "MEMENTO_FRIEDRICH_BAROQUE_VOLTAIRE_EDITS",
  "name": "Voltaire's Edits",
  "text": "Gain [B]50 [icon:YIELD_CULTURE][/B] when you spend an [icon:ATTRIBUTE] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Attribute[/TIP] Point on the [icon:ATTRIBUTE_CULTURAL] [TIP:LOC_PEDIA_CONCEPTS_ATTRIBUTE_TOOLTIP]Cultural Attribute[/TIP] tree.(Scales by Game Speed)",
  "quote": "To hold a pen is to be at war.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "FRIEDRICH_ALT",
  "unlock": "Unlock at Friedrich, Baroque level 5"
 },
 "Anti-Machiavel": {
  "id": "MEMENTO_FRIEDRICH_BAROQUE_ANTI_MACHIAVEL",
  "name": "Anti-Machiavel",
  "text": "+2 free [icon:WAR_SUPPORT] [TIP:LOC_PEDIA_CONCEPTS_WAR_SUPPORT_TOOLTIP]War Support[/TIP] on all wars declared against you.",
  "quote": "The capacity to do good.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "FRIEDRICH_ALT",
  "unlock": "Unlock at Friedrich, Baroque level 9"
 },
 "Incense Censer": {
  "id": "MEMENTO_XERXES_ACHAEMENID_INCENSE_CENSER",
  "name": "Incense Censer",
  "text": "[B]+2 [icon:YIELD_CULTURE][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for every active [icon:TRADE_ROUTE] [TIP:LOC_PEDIA_CONCEPTS_TRADE_ROUTE_TOOLTIP]Trade Route[/TIP].",
  "quote": "Divine intermediary.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "XERXES_ALT",
  "unlock": "Unlock at Xerxes, the Achaemenid level 2"
 },
 "Gold Fluted Phiale": {
  "id": "MEMENTO_XERXES_ACHAEMENID_GOLD_FLUTED_PHIALE",
  "name": "Gold Fluted Phiale",
  "text": "[B]+1 [icon:TRADE_ROUTE][/B] [TIP:LOC_PEDIA_CONCEPTS_TRADE_ROUTE_TOOLTIP]Trade Route[/TIP] Limit with all other Leaders.",
  "quote": "Lobed bowl, regal gift.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "XERXES_ALT",
  "unlock": "Unlock at Xerxes, the Achaemenid level 5"
 },
 "Chalcedony Seal": {
  "id": "MEMENTO_XERXES_ACHAEMENID_CHALCEDONY_SEAL",
  "name": "Chalcedony Seal",
  "text": "[B]+1 [icon:YIELD_CULTURE][/B] and [icon:YIELD_GOLD] on [TIP:LOC_PEDIA_CONCEPTS_UNIQUE_BUILDING_TOOLTIP]Unique Buildings[/TIP] and [icon:CITY_RURAL] [TIP:LOC_PEDIA_CONCEPTS_IMPROVEMENT_TOOLTIP]Improvements[/TIP].",
  "quote": "Carved depiction of a great king.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "XERXES_ALT",
  "unlock": "Unlock at Xerxes, the Achaemenid level 9"
 },
 "Paiza": {
  "id": "MEMENTO_GENGHIS_KHAN_PAIZA",
  "name": "Paiza",
  "text": "[B]-1 [icon:YIELD_GOLD][/B] [TIP:LOC_PEDIA_CONCEPTS_MAINTENANCE_TOOLTIP]Maintenance[/TIP] on [TIP:LOC_PEDIA_CONCEPTS_CAVALRY_UNITS_TOOLTIP]Cavalry Units[/TIP]",
  "quote": "Tax-free and ready to ride.",
  "tag": "Expansionist",
  "tier": "1",
  "level": 2,
  "path": "GENGHIS_KHAN",
  "unlock": "Unlock at Genghis Khan level 2"
 },
 "Saddle": {
  "id": "MEMENTO_GENGHIS_KHAN_SADDLE",
  "name": "Saddle",
  "text": "[B]+1 [icon:YIELD_FOOD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [TIP:LOC_PEDIA_CONCEPTS_CAVALRY_UNITS_TOOLTIP]Cavalry Units[/TIP] [TIP:LOC_PEDIA_CONCEPTS_STATIONED_TOOLTIP]Stationed[/TIP] on a [TIP:LOC_PEDIA_CONCEPTS_PALACE_TOOLTIP]Palace[/TIP] or City Hall.",
  "quote": "Union of horse and warrior.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "GENGHIS_KHAN",
  "unlock": "Unlock at Genghis Khan level 5"
 },
 "Sulde": {
  "id": "MEMENTO_GENGHIS_KHAN_SULDE",
  "name": "Sulde",
  "text": "[B]+1 [icon:YIELD_CULTURE][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] on [TIP:LOC_PEDIA_CONCEPTS_CAVALRY_UNITS_TOOLTIP]Cavalry Units[/TIP] [TIP:LOC_PEDIA_CONCEPTS_STATIONED_TOOLTIP]Stationed[/TIP] on a [TIP:LOC_PEDIA_CONCEPTS_PALACE_TOOLTIP]Palace[/TIP] or [icon:YIELD_CITIES] [TIP:LOC_PEDIA_CONCEPTS_CITIES_TOOLTIP]City[/TIP] Hall.",
  "quote": "Banner of war.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "GENGHIS_KHAN",
  "unlock": ""
 },
 "Magic Plant": {
  "id": "MEMENTO_GILGAMESH_MAGIC_PLANT",
  "name": "Magic Plant",
  "text": "Friendly greetings give [B]+100% [icon:RELATIONSHIP][/B] [TIP:LOC_PEDIA_CONCEPTS_RELATIONSHIP_TOOLTIP]Relationship[/TIP] increase.",
  "quote": "The key to immortality.",
  "tag": "Diplomatic",
  "tier": "1",
  "level": 2,
  "path": "GILGAMESH",
  "unlock": "Unlock at Gilgamesh level 2"
 },
 "Pukku": {
  "id": "MEMENTO_GILGAMESH_PUKKU",
  "name": "Pukku",
  "text": "[B]+2 [icon:YIELD_HAPPINESS][/B] in all [TIP:LOC_PEDIA_CONCEPTS_SETTLEMENT_TOOLTIP]Settlements[/TIP] while you have exactly one [icon:PLAYER_RELATIONSHIP_ALLIANCE] [TIP:LOC_PEDIA_CONCEPTS_ALLIANCE_TOOLTIP]Ally[/TIP].",
  "quote": "Once loved, once lost.",
  "tag": "Diplomatic",
  "tier": "1",
  "level": 5,
  "path": "GILGAMESH",
  "unlock": "Unlock at Gilgamesh level 5"
 },
 "Mikku": {
  "id": "MEMENTO_GILGAMESH_MIKKU",
  "name": "Mikku",
  "text": "[B]+1 [icon:YIELD_DIPLOMACY][/B] in all [TIP:LOC_PEDIA_CONCEPTS_SETTLEMENT_TOOLTIP]Settlements[/TIP] while you have exactly one [icon:PLAYER_RELATIONSHIP_ALLIANCE] [TIP:LOC_PEDIA_CONCEPTS_ALLIANCE_TOOLTIP]Ally[/TIP].",
  "quote": "Inanna's gift.",
  "tag": "Diplomatic",
  "tier": "1",
  "level": 9,
  "path": "GILGAMESH",
  "unlock": "Unlock at Gilgamesh level 9"
 },
 "Dhal": {
  "id": "MEMENTO_LAKSHMIBAI_DHAL",
  "name": "Dhal",
  "text": "[B]+2 [icon:NAR_REW_COMBAT][/B] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] defending in friendly territory.",
  "quote": "Round protector.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "LAKSHMIBAI",
  "unlock": "Unlock at Lakshmibai level 2"
 },
 "Baadal's Reins": {
  "id": "MEMENTO_LAKSHMIBAI_BAADALS_REINS",
  "name": "Baadal's Reins",
  "text": "[B]+1 [icon:YIELD_DIPLOMACY][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] per Pasture [icon:CITY_RURAL] [TIP:LOC_PEDIA_CONCEPTS_IMPROVEMENT_TOOLTIP]Improvement[/TIP].",
  "quote": "Remembrance of a loyal steed.",
  "tag": "Diplomatic",
  "tier": "1",
  "level": 5,
  "path": "LAKSHMIBAI",
  "unlock": "Unlock at Lakshmibai level 5"
 },
 "Flag of Jhansi": {
  "id": "MEMENTO_LAKSHMIBAI_FLAG_OF_JHANSI",
  "name": "Flag of Jhansi",
  "text": "[B]+2 [icon:YIELD_DIPLOMACY][/B] for each [icon:UNIT_ARMY_COMMANDER] [TIP:LOC_PEDIA_CONCEPTS_COMMANDER_TOOLTIP]Army Commander[/TIP] [TIP:LOC_PEDIA_CONCEPTS_PROMOTION_TOOLTIP]Promotion[/TIP].",
  "quote": "Symbol of the people.",
  "tag": "Diplomatic",
  "tier": "1",
  "level": 9,
  "path": "LAKSHMIBAI",
  "unlock": "Unlock at Lakshmibai level 9"
 },
 "Portrait of Josephine": {
  "id": "MEMENTO_NAPOLEON_EMPEROR_PORTRAIT_JOSEPHINE",
  "name": "Portrait of Josephine",
  "text": "[B]+2 [icon:YIELD_GOLD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for every Leader you are Unfriendly or Hostile with.",
  "quote": "You alone rule my heart.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "NAPOLEON",
  "unlock": "Unlock at Napoleon Emperor level 2"
 },
 "Green Colonel's Jacket": {
  "id": "MEMENTO_NAPOLEON_EMPEROR_GREEN_COLONEL_JACKET",
  "name": "Green Colonel's Jacket",
  "text": "[B]+1 [icon:YIELD_GOLD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] per [icon:TRADE_ROUTE] [TIP:LOC_PEDIA_CONCEPTS_TRADE_ROUTE_TOOLTIP]Trade Route[/TIP], doubled if you have the highest number of [icon:TRADE_ROUTE] Trade Routes.",
  "quote": "Like the Chasseurs à Cheval.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "NAPOLEON",
  "unlock": "Unlock at Napoleon Emperor level 5"
 },
 "Crown of Napoleon": {
  "id": "MEMENTO_NAPOLEON_EMPEROR_CROWN_OF_NAPOLEON",
  "name": "Crown of Napoleon",
  "text": "Gain [B]200 [icon:YIELD_GOLD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] when a [icon:WAR] [TIP:LOC_PEDIA_CONCEPTS_FORMAL_WAR_TOOLTIP]Formal War[/TIP] is declared against you.",
  "quote": "Coronation of the Emperor.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "NAPOLEON",
  "unlock": "Unlock at Napoleon Emperor level 9"
 },
 "Artilleryman's Gloves": {
  "id": "MEMENTO_NAPOLEON_REVOLUTIONARY_ARTILLERYMAN_GLOVES",
  "name": "Artilleryman's Gloves",
  "text": "[B]+2 [icon:YIELD_CULTURE][/B] for each [icon:UNIT_ARMY_COMMANDER] [TIP:LOC_PEDIA_CONCEPTS_COMMANDER_TOOLTIP]Army Commander[/TIP] [TIP:LOC_PEDIA_CONCEPTS_PROMOTION_TOOLTIP]Promotion[/TIP].",
  "quote": "Face cannon fire for the fallen.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "NAPOLEON_ALT",
  "unlock": ""
 },
 "Bicorne Hat": {
  "id": "MEMENTO_NAPOLEON_REVOLUTIONARY_BICORNE_HAT",
  "name": "Bicorne Hat",
  "text": "[B]+1 [icon:Action_Move] Movement[/B] for [TIP:LOC_PEDIA_CONCEPTS_INFANTRY_UNITS_TOOLTIP]Infantry Units[/TIP].",
  "quote": "Worn side-to-side.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "NAPOLEON_ALT",
  "unlock": "Unlock at Napoleon Revolutionary level 5"
 },
 "Legion d'honneur Grand Eagle and Cross": {
  "id": "MEMENTO_NAPOLEON_REVOLUTIONARY_LEGION_DHONNEUR_GRAND_EAGLE_CROSS",
  "name": "Legion d'honneur Grand Eagle and Cross",
  "text": "Units in a [TIP:LOC_PEDIA_CONCEPTS_COMMAND_RADIUS_TOOLTIP]Command Radius[/TIP] [icon:Action_Heal] Heal [B]+10 [icon:Action_Heal] HP[/B] after defeating an enemy Unit.",
  "quote": "With such baubles, men are led.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "NAPOLEON_ALT",
  "unlock": "Unlock at Napoleon Revolutionary level 9"
 },
 "Nimcha": {
  "id": "MEMENTO_SAYYIDA_AL_HURRA_NIMCHA",
  "name": "Nimcha",
  "text": "[B]-1 [icon:YIELD_GOLD][/B] [TIP:LOC_PEDIA_CONCEPTS_MAINTENANCE_TOOLTIP]Maintenance[/TIP] on [TIP:LOC_PEDIA_CONCEPTS_NAVAL_UNITS_TOOLTIP]Naval Units[/TIP].",
  "quote": "A blade for land and ship.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "SAYYIDA_AL_HURRA",
  "unlock": ""
 },
 "Mithqāl": {
  "id": "MEMENTO_SAYYIDA_AL_HURRA_MITHQAL",
  "name": "Mithqāl",
  "text": "[B]+2 [icon:YIELD_GOLD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] in [TIP:LOC_PEDIA_CONCEPTS_SETTLEMENT_TOOLTIP]Settlements[/TIP] with a Naval Unit [TIP:LOC_PEDIA_CONCEPTS_STATIONED_TOOLTIP]Stationed[/TIP] on a [icon:CITY_URBAN] [TIP:LOC_PEDIA_CONCEPTS_DISTRICT_TOOLTIP]District[/TIP].",
  "quote": "The weight of currency.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "SAYYIDA_AL_HURRA",
  "unlock": ""
 },
 "Gazelle Vase": {
  "id": "MEMENTO_SAYYIDA_AL_HURRA_GAZELLE_VASE",
  "name": "Gazelle Vase",
  "text": "Gain [B]25 [icon:YIELD_CULTURE][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] for every Diplomatic Action accepted by another Leader.",
  "quote": "Granadan artistry.",
  "tag": "Diplomatic",
  "tier": "1",
  "level": 9,
  "path": "SAYYIDA_AL_HURRA",
  "unlock": ""
 },
 "Poteskwate": {
  "id": "MEMENTO_TECUMSEH_POTESKWATE",
  "name": "Poteskwate",
  "text": "[B]+1 [icon:YIELD_FOOD][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] in [icon:YIELD_TOWNS] [TIP:LOC_PEDIA_CONCEPTS_TOWN_TOOLTIP]Towns[/TIP] for each [icon:CITYSTATE] [TIP:LOC_PEDIA_CONCEPTS_CITY_STATE_TOOLTIP]City-State[/TIP] you are [TIP:LOC_PEDIA_CONCEPTS_SUZERAIN_TOOLTIP]Suzerain[/TIP] of.",
  "quote": "Arboreal mortar and pestle.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "TECUMSEH",
  "unlock": "Unlock at Tecumseh level 2"
 },
 "Warclub": {
  "id": "MEMENTO_TECUMSEH_WARCLUB",
  "name": "Warclub",
  "text": "[B]+1 [icon:NAR_REW_COMBAT][/B] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] for [TIP:LOC_PEDIA_CONCEPTS_INFANTRY_UNITS_TOOLTIP]Infantry Units[/TIP] for every [icon:CITYSTATE] [TIP:LOC_PEDIA_CONCEPTS_CITY_STATE_TOOLTIP]City-State[/TIP] you are [TIP:LOC_PEDIA_CONCEPTS_SUZERAIN_TOOLTIP]Suzerain[/TIP] of.",
  "quote": "Sleep not longer.",
  "tag": "Military",
  "tier": "1",
  "level": 9,
  "path": "TECUMSEH",
  "unlock": "Unlock at Tecumseh level 5"
 },
 "Wampum Belt": {
  "id": "MEMENTO_TECUMSEH_WAMPUM_BELT",
  "name": "Wampum Belt",
  "text": "[B]+1 [icon:YIELD_PRODUCTION][/B] per [TIP:LOC_PEDIA_CONCEPTS_AGE_TOOLTIP]Age[/TIP] in [icon:YIELD_CITIES] [TIP:LOC_PEDIA_CONCEPTS_CITIES_TOOLTIP]Cities[/TIP] for each [icon:CITYSTATE] [TIP:LOC_PEDIA_CONCEPTS_CITY_STATE_TOOLTIP]City-State[/TIP] you are [TIP:LOC_PEDIA_CONCEPTS_SUZERAIN_TOOLTIP]Suzerain[/TIP] of.",
  "quote": "Symbol of union.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "TECUMSEH",
  "unlock": "Unlock at Tecumseh level 9"
 },
 "Kabuto": {
  "id": "MEMENTO_TOYOTOMI_HIDEYOSHI_KABUTO",
  "name": "Kabuto",
  "text": "[B]+3 [icon:YIELD_DIPLOMACY][/B] per [B]Age[/B].",
  "quote": "Requires regular watering.",
  "tag": "Diplomatic",
  "tier": "1",
  "level": 2,
  "path": "TOYOTOMI_HIDEYOSHI",
  "unlock": ""
 },
 "Honebami": {
  "id": "MEMENTO_TOYOTOMI_HIDEYOSHI_HONEBAMI",
  "name": "Honebami",
  "text": "[B]+1 [icon:Action_Move] Movement[/B] on Tier 3 Units.",
  "quote": "The bone-eater.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "TOYOTOMI_HIDEYOSHI",
  "unlock": ""
 },
 "Tea Ceremony Kit": {
  "id": "MEMENTO_TOYOTOMI_HIDEYOSHI_TEA_CEREMONY_KIT",
  "name": "Tea Ceremony Kit",
  "text": "[B]+20% [icon:YIELD_PRODUCTION][/B] towards constructing Altars, Temples, and Museums.",
  "quote": "Wabi-sabi in a cup.",
  "tag": "Cultural",
  "tier": "1",
  "level": 9,
  "path": "TOYOTOMI_HIDEYOSHI",
  "unlock": ""
 },
 "Geobukseon Blueprint": {
  "id": "MEMENTO_YI_SUN_SIN_GEOBUKSEON_BLUEPRINT",
  "name": "Geobukseon Blueprint",
  "text": "[B]+2 [icon:NAR_REW_COMBAT] Combat Strength[/B] to [B]Naval Units[/B] while defending.",
  "quote": "Beware the dragon's head.",
  "tag": "Military",
  "tier": "1",
  "level": 2,
  "path": "YI_SUN_SIN",
  "unlock": ""
 },
 "Janggeom": {
  "id": "MEMENTO_YI_SUN_SIN_JANGGEOM",
  "name": "Janggeom",
  "text": "+20% [B]Fleet Commander[/B] [B]XP[/B].",
  "quote": "To stain the mountains and rivers.",
  "tag": "Military",
  "tier": "1",
  "level": 5,
  "path": "YI_SUN_SIN",
  "unlock": ""
 },
 "Nanjung Ilgi": {
  "id": "MEMENTO_YI_SUN_SIN_NANJUNG_ILGI",
  "name": "Nanjung Ilgi",
  "text": "[B]+20% [icon:YIELD_PRODUCTION][/B] towards constructing [icon:YIELD_SCIENCE] [B]Science Buildings[/B].",
  "quote": "The words of the Admiral.",
  "tag": "Scientific",
  "tier": "1",
  "level": 9,
  "path": "YI_SUN_SIN",
  "unlock": ""
 }
};
