// Auto-generated by tools/build_unit_attrs.py.
// Per-unit Attributes: fandom's curated "Attributes:" list where one exists
// (tools/unit_attrs_fandom.json), else derived from the Civ VII game data.
// Verify with tools/audit_unit_attrs.py.
window.CIVPEDIA_UNIT_ATTRS = {
 "UNIT_WARRIOR": [
  "Exerts a Zone of Control."
 ],
 "UNIT_SPEARMAN": [
  "Exerts a Zone of Control."
 ],
 "UNIT_CHARIOT": [
  "Exerts a Zone of Control."
 ],
 "UNIT_GALLEY": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_PHALANX": [
  "Exerts a Zone of Control."
 ],
 "UNIT_HORSEMAN": [
  "Exerts a Zone of Control."
 ],
 "UNIT_QUADRIREME": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_DANTINAS_TATHA": [
  "Exerts a Zone of Control.",
  "Immune to Flood Damage."
 ],
 "UNIT_DHOW": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore.",
  "+4 [icon:NAR_REW_COMBAT] Combat Strength on Coast.",
  "Higher [icon:BOMBARD_STRENGTH] Bombard Strength.",
  "Can cross Borders of other Civilizations.",
  "Has 1 charge to create a naval [icon:TRADE_ROUTE] Trade Route."
 ],
 "UNIT_HOPLITE": [
  "Exerts a Zone of Control.",
  "+2 [icon:NAR_REW_COMBAT] Combat Strength if adjacent to another Hoplite."
 ],
 "UNIT_IMMORTAL": [
  "Exerts a Zone of Control.",
  "Heals 15 HP after defeating an enemy Unit."
 ],
 "UNIT_LEGION": [
  "Exerts a Zone of Control.",
  "+1 [icon:NAR_REW_COMBAT] Combat Strength for every Tradition in the Government."
 ],
 "UNIT_MEDJAY": [
  "Exerts a Zone of Control.",
  "+3 [icon:NAR_REW_COMBAT] Combat Strength in friendly Territory, doubled when stationed in a Settlement.",
  "Tier 2 and Tier 3 Medjay have no Maintenance Cost."
 ],
 "UNIT_NU": [
  "Exerts a Zone of Control.",
  "+5 [icon:RANGED_STRENGTH] Ranged Strength when targeting adjacent Units."
 ],
 "UNIT_PURABHETTARAH": [
  "Exerts a Zone of Control.",
  "+5 [icon:NAR_REW_COMBAT] Combat Strength against [icon:CITY_FORTIFIED] Fortified Districts."
 ],
 "UNIT_FOEDERATI": [
  "Exerts a Zone of Control.",
  "Cost scales with the number of Foederati trained.",
  "+2 [icon:NAR_REW_COMBAT] Combat Strength for each adjacent Military Unit."
 ],
 "UNIT_HAZARAPATIS": [
  "Can be attacked by enemy units.",
  "Can Assemble and Deploy Land Units +1 Civilian Unit.",
  "Can command Land Units.",
  "Starts with the [icon:NAR_REW_PROMOTION] Initiative Promotion, allowing packed Units to act immediately after deployment.",
  "Exerts a Zone of Control."
 ],
 "UNIT_JAGUAR_SLAYER": [
  "Can Auto-Explore.",
  "Ignores [icon:ACTION_MOVE] Movement penalties from [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_ROUGH_TERRAIN_TOOLTIP]Rough[/TIP], [TIP:LOC_PEDIA_CONCEPTS_VEGETATED_TERRAIN_TOOLTIP]Vegetated[/TIP], and [TIP:LOC_SYN_WET_TERRAIN]Wet[/TIP] [B]Terrain[/B].",
  "Has 20 [icon:NAR_REW_COMBAT] Combat Strength and can initiate combat.",
  "Counts as a Military Unit."
 ],
 "UNIT_LEGATUS": [
  "Can be attacked by enemy Units.",
  "Can Assemble and Deploy Land Units +1 Civilian Unit.",
  "Can command Land Units.",
  "Exerts a Zone of Control."
 ],
 "UNIT_NAGARIKA": [
  "Can be attacked by enemy Units.",
  "Grants extra [icon:YIELD_HAPPINESS] Happiness to newly Founded Settlements."
 ],
 "UNIT_TANKWA": [
  "Replaces the Merchant after creating a [icon:TRADE_ROUTE] Trade Route on water.",
  "Moves automatically.",
  "+2 [icon:ACTION_SHOWALL] Sight."
 ],
 "UNIT_VAISHYA": [
  "Turns into a Trade Caravan or Trade Ship after creating a [icon:TRADE_ROUTE] Trade Route.",
  "Ignores [icon:ACTION_MOVE] Movement penalties from Wet Terrain.",
  "Immune to Flood Damage."
 ],
 "UNIT_WATONATHI": [
  "Turns into a Trade Caravan or Trade Ship after creating a [icon:TRADE_ROUTE] Trade Route.",
  "Grants 25 [icon:YIELD_GOLD] Gold per Resource acquired when creating a [icon:TRADE_ROUTE] Trade Route."
 ],
 "UNIT_HERODOTUS": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SWORDSMAN": [
  "Exerts a Zone of Control."
 ],
 "UNIT_COURSER": [
  "Exerts a Zone of Control."
 ],
 "UNIT_COG": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_MAN_AT_ARMS": [
  "Exerts a Zone of Control."
 ],
 "UNIT_KNIGHT": [
  "Exerts a Zone of Control."
 ],
 "UNIT_CARRACK": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_PRIVATEER": [
  "Grants [icon:YIELD_GOLD] Gold when defeating a Unit equal to 100% of its [icon:NAR_REW_COMBAT] Combat Strength.",
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_PIKEMAN": [
  "Exerts a Zone of Control."
 ],
 "UNIT_LANCER": [
  "Exerts a Zone of Control."
 ],
 "UNIT_GALLEON": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_TREASURE_FLEET": [
  "Can transport Cargo from Distant Lands to homeland Settlements.",
  "Always Captured (Is captured by attacker when defeated in combat.)."
 ],
 "UNIT_ALEXANDER_VON_HUMBOLDT": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_CETBANG": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore.",
  "+5 [icon:NAR_REW_COMBAT] Combat Strength against Naval Units.",
  "Can pillage within 2 tiles for 1 [icon:ACTION_MOVE] Movement."
 ],
 "UNIT_CHEVALER": [
  "Exerts a Zone of Control.",
  "+3 [icon:NAR_REW_COMBAT] Combat Strength against slower Units."
 ],
 "UNIT_GOLD_BANGLES": [
  "Exerts a Zone of Control.",
  "+5 [icon:NAR_REW_COMBAT] Combat Strength on Resource tiles.",
  "+100% [icon:YIELD_GOLD] Gold from plundering [icon:TRADE_ROUTE] Trade Routes."
 ],
 "UNIT_KALAM": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_KESHIG": [
  "Counts as a Cavalry Unit.",
  "Ignores Zone of Control."
 ],
 "UNIT_LEIOMANO": [
  "Exerts a Zone of Control.",
  "+3 [icon:NAR_REW_COMBAT] Combat Strength against Infantry Units and [icon:MILITARY] [TIP:LOC_PEDIA_CONCEPTS_CAVALRY_UNITS_TOOLTIP]Cavalry[/TIP] [B]Units[/B].",
  "+5 [icon:NAR_REW_COMBAT] Combat Strength when defending against Heavy Naval Units."
 ],
 "UNIT_MAMLUK": [
  "Exerts a Zone of Control.",
  "Has [TIP:LOC_PEDIA_CONCEPTS_SKIRMISH_TOOLTIP]Skirmish[/TIP] ability.",
  "+5 [icon:NAR_REW_COMBAT] Combat Strength in Towns and Cities with at least 5 [icon:SPECIALIST] Specialists."
 ],
 "UNIT_TERCIO": [
  "Exerts a Zone of Control.",
  "Adjacent Units receive +3 [icon:NAR_REW_COMBAT] Combat Strength against Cavalry Units (bonus is only applied once)."
 ],
 "UNIT_WARAKAQ": [
  "Ignores [icon:ACTION_MOVE] Movement penalties from Rough Terrain.",
  "+5 [icon:RANGED_STRENGTH] Ranged Strength when attacking from Rough Terrain."
 ],
 "UNIT_XUNLEICHONG": [
  "Exerts a Zone of Control.",
  "+4 [icon:NAR_REW_COMBAT] Combat Strength in featureless tiles."
 ],
 "UNIT_CORSAIR": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore.",
  "Captures opposing Naval Units when it defeats them."
 ],
 "UNIT_CHASQUI": [
  "Can be attacked by enemy Units.",
  "Ignores [icon:ACTION_MOVE] Movement penalties from [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_ROUGH_TERRAIN_TOOLTIP]Rough[/TIP], [TIP:LOC_PEDIA_CONCEPTS_VEGETATED_TERRAIN_TOOLTIP]Vegetated[/TIP], and [TIP:LOC_SYN_WET_TERRAIN]Wet[/TIP] [B]Terrain[/B].",
  "Can Auto-Explore."
 ],
 "UNIT_KAHUNA": [
  "Can Heal adjacent Units."
 ],
 "UNIT_MANDARIN": [
  "Turns into a Trade Caravan or Trade Ship after creating a [icon:TRADE_ROUTE] Trade Route."
 ],
 "UNIT_NOYAN": [
  "Can be attacked by enemy Units.",
  "Can Assemble and Deploy Land Units +1 Civilian Unit.",
  "Can command Land Units.",
  "Has increased [icon:ACTION_SHOWALL] Sight.",
  "+50% [icon:NAR_REW_COMBAT] Combat Strength from Flanking for Cavalry Units in the [icon:COMMANDER_RADIUS] Command Radius.",
  "Exerts a Zone of Control."
 ],
 "UNIT_OTTRU": [
  "Can be attacked by enemy units.",
  "Can Assemble and Deploy Naval Units.",
  "Can command naval units.",
  "Has +1 [icon:ACTION_MOVE] Movement and greater [icon:ACTION_SHOWALL] Sight.",
  "Reduces the [icon:NAR_REW_COMBAT] Combat Strength of enemy Military Units within its [icon:COMMANDER_RADIUS] Command Radius by -3.",
  "Exerts a Zone of Control."
 ],
 "UNIT_PEDANDA": [
  "Grants [icon:YIELD_CULTURE] Culture and [icon:YIELD_GOLD] Gold when converting a Settlement for the first time."
 ],
 "UNIT_SOKEMAN": [
  "Can be attacked by enemy Units.",
  "Can Found Settlements starting with walls."
 ],
 "UNIT_TAJIRO": [
  "Turns into a Trade Caravan or Trade Ship after creating a [icon:TRADE_ROUTE] Trade Route."
 ],
 "UNIT_ALIM": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_ALIM_AL_JAHIZ": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_ALIM_AL_KHWARIZMI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_ALIM_IBN_SINA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_ALIM_AL_MAQDISI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_ALIM_AL_FARGHANI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_ALIM_AL_FARABI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_ALIM_RABIA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_ALIM_AL_SHAYBANI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_ALIM_AL_JAZARI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_ALIM_IBN_FADLAN": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_CONQUISTADOR_FERDINAND_MAGELLAN": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_CONQUISTADOR_FRANCISCO_PIZARRO": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_CONQUISTADOR_JUAN_PONCE_DE_LEON": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_CONQUISTADOR_CHRISTOPHER_COLUMBUS": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_CONQUISTADOR_HERNAN_CORTES": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_CONQUISTADOR_HERNANDO_DE_SOTO": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_CONQUISTADOR_FRANCISCO_DE_ORELLANA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_CONQUISTADOR_ALVAR_NUNEZ_CABEZA_DE_VACA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_CONQUISTADOR_MIGUEL_LOPEZ_DE_LEGAZPI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_CONQUISTADOR_SUAREZ": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_LINE_INFANTRY": [
  "Exerts a Zone of Control."
 ],
 "UNIT_CUIRASSIER": [
  "Exerts a Zone of Control."
 ],
 "UNIT_IRONCLAD": [
  "Can Auto-Explore.",
  "Exerts a Zone of Control."
 ],
 "UNIT_FRIGATE": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_RIFLEMAN": [
  "Exerts a Zone of Control."
 ],
 "UNIT_LANDSHIP": [
  "Exerts a Zone of Control."
 ],
 "UNIT_CRUISER": [
  "Can Auto-Explore.",
  "Exerts a Zone of Control."
 ],
 "UNIT_DREADNOUGHT": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_INFANTRY_COMPANY": [
  "Exerts a Zone of Control."
 ],
 "UNIT_TANK": [
  "Exerts a Zone of Control."
 ],
 "UNIT_DESTROYER": [
  "Can Auto-Explore.",
  "Exerts a Zone of Control."
 ],
 "UNIT_BATTLESHIP": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_SUBMARINE": [
  "Cannot attack Land Units or Districts."
 ],
 "UNIT_ABAMBOWA": [
  "Exerts a Zone of Control.",
  "+10 Healing from pillaging any tile."
 ],
 "UNIT_CHANG_BEUN": [
  "Can perform a Range Attack twice.",
  "Exerts a Zone of Control."
 ],
 "UNIT_COSSACK": [
  "Exerts a Zone of Control.",
  "Does not replace other Cavalry Units.",
  "+4 [icon:NAR_REW_COMBAT] Combat Strength in friendly territory."
 ],
 "UNIT_GARDE_IMPERIALE": [
  "Exerts a Zone of Control.",
  "+2 [icon:NAR_REW_COMBAT] Combat Strength when within a friendly Army Commander's Radius.",
  "Has a Ranged attack."
 ],
 "UNIT_HUSSAR": [
  "Exerts a Zone of Control.",
  "Does not replace other Cavalry Units.",
  "+1 [icon:NAR_REW_COMBAT] Combat Strength for every remaining [icon:ACTION_MOVE] Movement point."
 ],
 "UNIT_KATYUSHA": [
  "Lower [icon:BOMBARD_STRENGTH] Bombard Strength.",
  "Exerts a Zone of Control."
 ],
 "UNIT_MIKASA": [
  "Exerts a Zone of Control.",
  "Can Auto-Explore.",
  "Has increased [icon:ACTION_MOVE] Movement.",
  "Has lower [icon:BOMBARD_STRENGTH] Bombard Strength.",
  "Has one extra life, respawning at 50% HP in the nearest friendly Settlement when destroyed for the first time."
 ],
 "UNIT_SEPOY": [
  "Exerts a Zone of Control.",
  "Has [icon:BOMBARD_STRENGTH] Bombard Strength.",
  "Has [icon:RANGED_STRENGTH] Ranged Strength."
 ],
 "UNIT_SOLDADERAS": [
  "Exerts a Zone of Control.",
  "Increases healing of adjacent Units by +10 [icon:Action_Heal] HP. (bonus is only applied once)."
 ],
 "UNIT_PARTISAN": [
  "Exerts a Zone of Control.",
  "Each one is slightly more expensive than the last.",
  "+5 [icon:NAR_REW_COMBAT] Combat Strength against civilizations with different Ideologies.",
  "+10 Healing in owned territory."
 ],
 "UNIT_MWAMI": [
  "Can be attacked by enemy Units.",
  "Can Assemble and Deploy Land Units +1 Civilian Unit.",
  "Can command Land Units.",
  "Land Units gain +100% Yields and Healing from Pillage within the [icon:COMMANDER_RADIUS] Command Radius.",
  "Exerts a Zone of Control."
 ],
 "UNIT_HANGSHANG": [
  "Grants additional [icon:YIELD_GOLD] Gold when creating Naval [icon:TRADE_ROUTE] Trade Routes."
 ],
 "UNIT_ZAMINDAR": [
  "Can be attacked by enemy Units.",
  "Grants additional Population when Founding Settlements."
 ],
 "UNIT_JACOBIN_BARRAS": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_JACOBIN_BILLAUD_VARENNE": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_JACOBIN_BRISSOT": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_JACOBIN_D_AELDERS": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_JACOBIN_DANTON": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_JACOBIN_DESMOULINS": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_JACOBIN_GOUGES": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_JACOBIN_MARAT": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_JACOBIN_ROBESPIERRE": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_JACOBIN_SAINT_JUST": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_REVOLUCIONARIO_AVILA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_REVOLUCIONARIO_GUERRERO": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_REVOLUCIONARIO_HERRERA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_REVOLUCIONARIO_HIDALGO": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_REVOLUCIONARIO_JIMENEZ": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_REVOLUCIONARIO_JUAREZ": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_REVOLUCIONARIO_MORELOS": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_REVOLUCIONARIO_SANTA_ANNA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_REVOLUCIONARIO_VILLA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_REVOLUCIONARIO_ZAPATA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_UPARAT_CHAKRABONGSE": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_UPARAT_ITSARASUNTHON": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_UPARAT_PHIBUN": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_UPARAT_PINKLAO": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_UPARAT_PRIDI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_UPARAT_RASMI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_UPARAT_SAKDIPHONLASEP": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_UPARAT_SENANURAK": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_UPARAT_VAJRAVUDH": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_UPARAT_WICHAICHAN": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_JOHN_MAYNARD_KEYNES": [
  "Provides 1000 GDP each time a World Bank Office is established in a Capital.",
  "Cannot take Damage under any circumstances, including nuclear strikes."
 ],
 "UNIT_SCOUT": [
  "Can Auto-Explore.",
  "Can be attacked by enemy Units.",
  "Ignores [icon:ACTION_MOVE] Movement penalties from Vegetated Terrain."
 ],
 "UNIT_ARMY_COMMANDER": [
  "Can be attacked by enemy Units.",
  "Can Assemble and Deploy Land Units +1 Civilian Unit.",
  "Can command Land Units.",
  "Exerts a Zone of Control.",
  "[B]Ageless[/B] — is not replaced or removed at an Age transition."
 ],
 "UNIT_FLEET_COMMANDER": [
  "Can be attacked by enemy Units.",
  "Can Assemble and Deploy Naval Units.",
  "Can command Naval Units.",
  "Exerts a Zone of Control.",
  "[B]Ageless[/B] — is not replaced or removed at an Age transition."
 ],
 "UNIT_SQUADRON_COMMANDER": [
  "Can be attacked by enemy Units.",
  "Can command Air Units.",
  "Exerts a Zone of Control.",
  "[B]Ageless[/B] — is not replaced or removed at an Age transition."
 ],
 "UNIT_TREASURE_FLEET_SMALL": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B]."
 ],
 "UNIT_FOUNDER": [
  "Can be attacked by enemy Units."
 ],
 "UNIT_SETTLER": [
  "Can be attacked by enemy Units."
 ],
 "UNIT_MERCHANT": [
  "Turns into a Trade Caravan or Trade Ship after creating a [icon:TRADE_ROUTE] Trade Route."
 ],
 "UNIT_TRADE_CARAVAN": [
  "Replaces the Merchant after creating a [icon:TRADE_ROUTE] Trade Route on land."
 ],
 "UNIT_TRADE_SHIP": [
  "Replaces the Merchant after creating a [icon:TRADE_ROUTE] Trade Route on water."
 ],
 "UNIT_MAGARRU": [
  "[icon:ACTION_MOVE] Suffers heavy Movement penalties in [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_ROUGH_TERRAIN_TOOLTIP]Rough[/TIP] or [TIP:LOC_PEDIA_CONCEPTS_VEGETATED_TERRAIN_TOOLTIP]Vegetated[/TIP] [B]Terrain[/B] without a road.",
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge)."
 ],
 "UNIT_MAGARRU_2": [
  "[icon:ACTION_MOVE] Suffers heavy Movement penalties in [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_ROUGH_TERRAIN_TOOLTIP]Rough[/TIP] or [TIP:LOC_PEDIA_CONCEPTS_VEGETATED_TERRAIN_TOOLTIP]Vegetated[/TIP] [B]Terrain[/B] without a road.",
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge)."
 ],
 "UNIT_TURTANU": [
  "Can be attacked by enemy Units.",
  "Can Assemble and Deploy Land Units +1 Civilian Unit.",
  "Can command Land Units.",
  "Infantry and Cavalry Units within the [icon:COMMANDER_RADIUS] Command Radius have +5 [icon:NAR_REW_COMBAT] Combat Strength against [icon:CITY_FORTIFIED] Fortified Districts.",
  "Exerts a Zone of Control."
 ],
 "UNIT_NUMIDIAN_CAVALRY": [
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control.",
  "+1 [icon:NAR_REW_COMBAT] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] for each [icon:RADIAL_RESOURCES] [B]Unique[/B] [TIP:LOC_PEDIA_CONCEPTS_CITY_RESOURCES_TOOLTIP]City Resource[/TIP] assigned to your [icon:NOTIFICATION_SELECT_CAPITAL] Capital."
 ],
 "UNIT_NUMIDIAN_CAVALRY_2": [
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control.",
  "+1 [icon:NAR_REW_COMBAT] [TIP:LOC_PEDIA_CONCEPTS_COMBAT_STRENGTH_TOOLTIP]Combat Strength[/TIP] for each [icon:RADIAL_RESOURCES] [B]Unique[/B] [TIP:LOC_PEDIA_CONCEPTS_CITY_RESOURCES_TOOLTIP]City Resource[/TIP] assigned to your [icon:NOTIFICATION_SELECT_CAPITAL] Capital."
 ],
 "UNIT_COLONIST": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units.",
  "+1 [icon:Action_Move] [TIP:LOC_PEDIA_CONCEPTS_EMBARK_TOOLTIP]Embarked[/TIP] Movement and +1 [icon:YIELD_POPULATION] Population if Settled adjacent to a [icon:RADIAL_RESOURCES] [TIP:LOC_PEDIA_CONCEPTS_RESOURCES_TOOLTIP]Resource[/TIP]."
 ],
 "UNIT_TOBANG": [
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control."
 ],
 "UNIT_TOBANG_2": [
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control."
 ],
 "UNIT_TOBANG_3": [
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control."
 ],
 "UNIT_HWACHA": [
  "[icon:ACTION_MOVE] Suffers heavy Movement penalties in [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_ROUGH_TERRAIN_TOOLTIP]Rough[/TIP] or [TIP:LOC_PEDIA_CONCEPTS_VEGETATED_TERRAIN_TOOLTIP]Vegetated[/TIP] [B]Terrain[/B] without a road."
 ],
 "UNIT_HWACHA_2": [
  "[icon:ACTION_MOVE] Suffers heavy Movement penalties in [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_ROUGH_TERRAIN_TOOLTIP]Rough[/TIP] or [TIP:LOC_PEDIA_CONCEPTS_VEGETATED_TERRAIN_TOOLTIP]Vegetated[/TIP] [B]Terrain[/B] without a road."
 ],
 "UNIT_HWACHA_3": [
  "[icon:ACTION_MOVE] Suffers heavy Movement penalties in [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_ROUGH_TERRAIN_TOOLTIP]Rough[/TIP] or [TIP:LOC_PEDIA_CONCEPTS_VEGETATED_TERRAIN_TOOLTIP]Vegetated[/TIP] [B]Terrain[/B] without a road."
 ],
 "UNIT_REVENGE": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_REVENGE_2": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_ANTIQUARIAN": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_YUMI": [
  "Exerts a Zone of Control."
 ],
 "UNIT_YUMI_2": [
  "Exerts a Zone of Control."
 ],
 "UNIT_SHIJIN": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHIJIN_NAKAYAMA_TADACHIKA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHIJIN_MURASAKI_SHIKIBU": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHIJIN_LADY_SARASHINA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHIJIN_SEI_SHONAGON": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHIJIN_IZUMI_SHIKIBUTIR": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHIJIN_MICHITSUNA_S_MOTHER": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHIJIN_OSHIKOCHI_NO_MITSUNE": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHIJIN_KI_NO_TOMONORI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHIJIN_KI_NO_TSURAYUKI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHIJIN_MIBU_NO_TADAMINE": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_VIKINGR": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_VIKINGR_2": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_VIKINGR_3": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_SAGA_HERO": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SAGA_HERO_EGILL_SKALLAGRIMSSON": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SAGA_HERO_GISLI_SURSSON": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SAGA_HERO_GRETTIR_ASMUNDARSON": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SAGA_HERO_KJARTAN_OLAFSSON": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SAGA_HERO_GUDRUN_OSVIFRSDOTTIR": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SAGA_HERO_HRAFNKELL_HALLFREDSSON": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SAGA_HERO_NJALL_THORGEIRSSON": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SAGA_HERO_GUNNAR_HAMUNDARSON": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SAGA_HERO_GUDRIDR_THORBJARNARDOTTIR": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SAGA_HERO_FREYDIS_EIRIKSDOTTIR": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_TURTLE_SHIP": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_TURTLE_SHIP_2": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_TURTLE_SHIP_3": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_GURKHA": [
  "Exerts a Zone of Control."
 ],
 "UNIT_GURKHA_2": [
  "Exerts a Zone of Control."
 ],
 "UNIT_GURKHA_3": [
  "Exerts a Zone of Control."
 ],
 "UNIT_SHERPA": [
  "Ignores [icon:ACTION_MOVE] Movement penalties from [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_ROUGH_TERRAIN_TOOLTIP]Rough[/TIP], [TIP:LOC_PEDIA_CONCEPTS_VEGETATED_TERRAIN_TOOLTIP]Vegetated[/TIP], and [TIP:LOC_SYN_WET_TERRAIN]Wet[/TIP] [B]Terrain[/B].",
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units.",
  "Can Auto-Explore."
 ],
 "UNIT_JANISSARY": [
  "Exerts a Zone of Control."
 ],
 "UNIT_JANISSARY_2": [
  "Exerts a Zone of Control."
 ],
 "UNIT_JANISSARY_3": [
  "Exerts a Zone of Control."
 ],
 "UNIT_BARBARY_CORSAIR": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore.",
  "[icon:NAR_REW_COMBAT] Combat Strength bonus when Flanking."
 ],
 "UNIT_BARBARY_CORSAIR_2": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore.",
  "[icon:NAR_REW_COMBAT] Combat Strength bonus when Flanking."
 ],
 "UNIT_BARBARY_CORSAIR_3": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore.",
  "[icon:NAR_REW_COMBAT] Combat Strength bonus when Flanking.",
  "Can see hidden enemy Units."
 ],
 "UNIT_SLOOP": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore.",
  "[icon:DIPLOMACY] Can move through other civilizations' territory without Open Borders.",
  "[icon:NAR_REW_COMBAT] Combat Strength bonus when Flanking."
 ],
 "UNIT_SLOOP_2": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore.",
  "[icon:DIPLOMACY] Can move through other civilizations' territory without Open Borders.",
  "[icon:NAR_REW_COMBAT] Combat Strength bonus when Flanking."
 ],
 "UNIT_SLOOP_3": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore.",
  "[icon:DIPLOMACY] Can move through other civilizations' territory without Open Borders.",
  "[icon:NAR_REW_COMBAT] Combat Strength bonus when Flanking."
 ],
 "UNIT_BUCCANEER": [
  "Can be attacked by enemy Units.",
  "Can Assemble and Deploy Naval Units.",
  "Can command Naval Units.",
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control."
 ],
 "UNIT_GHILMAN": [
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control."
 ],
 "UNIT_GHILMAN_2": [
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control."
 ],
 "UNIT_GHILMAN_3": [
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control."
 ],
 "UNIT_SOLTAN": [
  "Can be attacked by enemy Units.",
  "Can Assemble and Deploy Land Units +1 Civilian Unit.",
  "Can command Land Units.",
  "Has +1 [icon:ACTION_MOVE] Movement.",
  "While razing a Settlement, twice as many Districts are Razed per turn in Settlements where this Commander is on a District.",
  "Exerts a Zone of Control."
 ],
 "UNIT_SAMURAI": [
  "Exerts a Zone of Control."
 ],
 "UNIT_SAMURAI_2": [
  "Exerts a Zone of Control."
 ],
 "UNIT_SAMURAI_3": [
  "Exerts a Zone of Control."
 ],
 "UNIT_NINJA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units.",
  "Hidden from enemy Units unless they are adjacent."
 ],
 "UNIT_KISPOKO_NENA_TO": [
  "Exerts a Zone of Control."
 ],
 "UNIT_KISPOKO_NENA_TO_2": [
  "Exerts a Zone of Control."
 ],
 "UNIT_KISPOKO_NENA_TO_3": [
  "Exerts a Zone of Control."
 ],
 "UNIT_HOCEEPKILENI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_HWARANG": [
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control."
 ],
 "UNIT_HWARANG_2": [
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control."
 ],
 "UNIT_SANGDAEDEUNG": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units.",
  "[icon:DIPLOMACY] Can enter other civilizations' territory without Open Borders."
 ],
 "UNIT_KALIA": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_KALIA_2": [
  "Can only operate on [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_WATER_TERRAIN_TOOLTIP]water[/TIP] [B]tiles[/B].",
  "Exerts a Zone of Control.",
  "Can Auto-Explore."
 ],
 "UNIT_TEHINA": [
  "Ignores [icon:ACTION_MOVE] Movement penalties from [icon:TERRAIN_GENERIC] [TIP:LOC_PEDIA_CONCEPTS_ROUGH_TERRAIN_TOOLTIP]Rough[/TIP], [TIP:LOC_PEDIA_CONCEPTS_VEGETATED_TERRAIN_TOOLTIP]Vegetated[/TIP], and [TIP:LOC_SYN_WET_TERRAIN]Wet[/TIP] [B]Terrain[/B].",
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units.",
  "Can Auto-Explore."
 ],
 "UNIT_TRUNG_NHI": [
  "Can be attacked by enemy Units.",
  "Can Assemble and Deploy Land Units +1 Civilian Unit.",
  "Can command Land Units.",
  "[B]Ageless[/B] — is not replaced or removed at an Age transition.",
  "Respawns faster than other Commanders if defeated.",
  "Exerts a Zone of Control."
 ],
 "UNIT_TARKHAN": [
  "Can be attacked by enemy Units.",
  "Can Assemble and Deploy Land Units +1 Civilian Unit.",
  "Can command Land Units.",
  "Has +1 [icon:ACTION_MOVE] Movement.",
  "Units in its [icon:COMMANDER_RADIUS] Command Radius can Pillage for 1 [icon:ACTION_MOVE] Movement.",
  "Exerts a Zone of Control."
 ],
 "UNIT_BOLYAR": [
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control."
 ],
 "UNIT_BOLYAR_2": [
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control."
 ],
 "UNIT_BOLYAR_3": [
  "Exerts a Zone of Control.",
  "[icon:NAR_REW_COMBAT] Combat bonus when making an unobstructed attack from more than one tile away (Cavalry Charge).",
  "Ignores enemy Zone of Control."
 ],
 "UNIT_JANGYONGYOUNG": [
  "Can be attacked by enemy Units.",
  "Can Assemble and Deploy Land Units +1 Civilian Unit.",
  "Can command Land Units.",
  "Land Units in a [icon:NOTIFICATION_SELECT_CAPITAL] Capital receive +5 [icon:NAR_REW_COMBAT] Combat Strength within the [icon:COMMANDER_RADIUS] Command Radius.",
  "Exerts a Zone of Control."
 ],
 "UNIT_QUAN_VUONG": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_BURNING_ARROW": [
  "+3 [icon:RANGED_STRENGTH] Ranged Strength against Siege Units.",
  "Applies the Burning status to a tile for 2 turns when performing a Range Attack."
 ],
 "UNIT_HULCHE": [
  "Can see through Vegetation.",
  "Ignores [icon:ACTION_MOVE] Movement penalties from Vegetated Terrain."
 ],
 "UNIT_BIPLANE": [
  "Cannot move independently on the map.",
  "Can only Rebase to and operate from [B]Aircraft[/B] Commanders.",
  "Can intercept enemy Air Units."
 ],
 "UNIT_BOMBER": [
  "Cannot move independently on the map.",
  "Can only Rebase to and operate from [B]Aircraft[/B] Commanders.",
  "Can Air Strike any District in Range."
 ],
 "UNIT_HEAVY_BOMBER": [
  "Cannot move independently on the map.",
  "Can only Rebase to and operate from [B]Aircraft[/B] Commanders.",
  "Can Air Strike any District in Range."
 ],
 "UNIT_TRENCH_FIGHTER": [
  "Cannot move independently on the map.",
  "Can only Rebase to and operate from [B]Aircraft[/B] Commanders."
 ],
 "UNIT_GUSA": [
  "Exerts a Zone of Control.",
  "+4 [icon:NAR_REW_COMBAT] Combat Strength if adjacent to another Gusa."
 ],
 "UNIT_PROSPECTOR": [
  "Can use Claim Resource action to claim a land Resource within 5 tiles of a Settlement, consuming the unit.",
  "Cost increases with each Prospector trained."
 ],
 "UNIT_STUKA": [
  "Cannot move independently on the map.",
  "Can only Rebase to and operate from [B]Aircraft[/B] Commanders.",
  "+3 [icon:RANGED_STRENGTH] Ranged Strength against Land Units.",
  "Lower [icon:ACTION_MOVE] Movement."
 ],
 "UNIT_ZERO": [
  "Cannot move independently on the map.",
  "Can only Rebase to and operate from [B]Aircraft[/B] Commanders.",
  "Can intercept enemy Air Units.",
  "Lower [icon:ACTION_MOVE] Movement.",
  "Has +4 [icon:NAR_REW_COMBAT] Combat Strength against other Fighters."
 ],
 "UNIT_DIVEBOMBER": [
  "Cannot move independently on the map.",
  "Can only Rebase to and operate from [B]Aircraft[/B] Commanders."
 ],
 "UNIT_CARRIER_COMMANDER": [
  "Can be attacked by enemy Units.",
  "Can command Air Units.",
  "Exerts a Zone of Control.",
  "[B]Ageless[/B] — is not replaced or removed at an Age transition."
 ],
 "UNIT_AERODROME_COMMANDER": [
  "Cannot move — it is created automatically, bound to its Aerodrome building.",
  "Can command Air Units.",
  "Cannot be attacked or damaged directly; it is destroyed only if its Aerodrome is removed.",
  "[B]Ageless[/B] — is not replaced or removed at an Age transition."
 ],
 "UNIT_CONQUISTADOR": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_JACOBIN": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_LOGIOS": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_LOGIOS_ARETE": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_LOGIOS_ARISTOTLE": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_LOGIOS_ASPASIA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_LOGIOS_HYPATIA": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_LOGIOS_PLATO": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_LOGIOS_PYTHAGORAS": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_LOGIOS_SAPPHO": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_LOGIOS_SOCRATES": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_LOGIOS_THALES": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_LOGIOS_XENOPHON": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_REVOLUCIONARIO": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHI_DAFU": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHI_DAFU_BAN_ZHAO": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHI_DAFU_HAN_FEI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHI_DAFU_LAOZI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHI_DAFU_MENCIUS": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHI_DAFU_MOZI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHI_DAFU_SHANG_YANG": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHI_DAFU_SHEN_BUHAI": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHI_DAFU_WANG_YANGMING": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHI_DAFU_XUN_KUANG": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_SHI_DAFU_ZHANG_HENG": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_TJATY": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_TJATY_AMHOSE": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_TJATY_APEREL": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_TJATY_HEMIUNU": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_TJATY_IMHOTEP": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_TJATY_KHAY": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_TJATY_NEBET": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_TJATY_PASER": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_TJATY_PTAHHOTEP": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_TJATY_RAMOSE": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_TJATY_USERAMEN": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
 "UNIT_UPARAT": [
  "[icon:UNIT_CAUTION] Cannot attack. Can be attacked by enemy Units."
 ],
};
